### ISSUE TITLE
[Suggestion] Seasons

### ISSUE THREAD

**Issue by 92slavik** [DarkPacks/SevTech-Ages#1089]
I dont know where i can post suggestions... i was thinking, what if you add some kind of a seasons mod? just without the thirst and stuff?.... 
-again, sorry i wasnt sure where to post this suggestion ;)

**Comment by justinrusso** [comment]
Suggestions are welcome here! Just note that these are generally not at the top of our list currently and that not every mod will make it into the pack :)

**Comment by artdude543** [comment]
I've gone over the options for mods which offer this kind of function, and I don't feel it's needed/meets the requirements for the pack. In terms of we don't force anything around seasons wise. It's more of a "look good" addon rather than content.

With this, the mods also add some impact to the loading/running of the game. Which the pack is already a fair beast to run, and I don't feel this is warranted to make users games take longer to load/run for a such a small change.

But thanks for your suggestion! We are quite picky about the mods added to the pack. But you are free to add your own mods on top for aesthetics and what not.
