### ISSUE TITLE
Shadow Gem Achievment

### ISSUE THREAD

**Issue by crocman** [DarkPacks/SevTech-Ages#1404]
Modpack Version: 3.04
Java Version: 1.8.0_161
Launcher Used: Twitch
Resourcepack Enabled?: SEUS Shaders
Optifine Installed?: Yes

I created a shadow gem and I didn't get the achievement. Do I need to get more than one or kill the Show creature to get achievement?

Thanks

 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by justinrusso** [comment]
It should be on inventory change
1. try dropping it and picking it back up
2. check the id of the item: is it `abyssalcraft:shadowgem:1`?

**Comment by artdude543** [comment]
Hello!

This appears to be an older issue on an old version of the modpack. This issue may have been fixed in later versions of the modpack, so we recommend that you update! If however, you are still having the same issue.

Please re-file an issue following the template and provide as much detail as you can. 

Thanks in advance and thank you for playing SevTech Ages!
