### ISSUE TITLE
Golden Bone tools all showing in age 2, but some are staged in 2 or 3, with all requiring items from 3.

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#1504]
Golden bone tools are all showing up in Age 2, but require items from Stage 3.
The Shovel, Hoe, and Hammer are all Staged in 2, should be changed to the stages of the rest of the items.

Version 3.0.4

**Comment by artdude543** [comment]
Hello!

This appears to be an older issue on an old version of the modpack. This issue may have been fixed in later versions of the modpack, so we recommend that you update! If however, you are still having the same issue.

Please re-file an issue following the template and provide as much detail as you can. 

Thanks in advance and thank you for playing SevTech Ages!
