### ISSUE TITLE
Server restarting very few minutes. 3.0.4

### ISSUE THREAD

**Issue by SnowMntGaming** [DarkPacks/SevTech-Ages#1513]
## Issue / Bug

https://pastebin.com/L6ptMS3C 
Server runs for about 5 mins then shuts down and restarts. 

## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: Twitch

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: N/A
* Optifine Installed?: N/A

## Server Information
* Java Version: 8 
* Operating System: Linux
* Hoster/Hosting Soultion: Nitrado
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: N/A

**Comment by justinrusso** [comment]
1. What version of Java 8?
2. Reinstall the modpack

**Comment by Darkosto** [comment]
May I ask if you updated forge beyond the version I packaged with the modpack?

**Comment by artdude543** [comment]
Hello!

This appears to be an older issue on an old version of the modpack. This issue may have been fixed in later versions of the modpack, so we recommend that you update! If however, you are still having the same issue.

Please re-file an issue following the template and provide as much detail as you can. 

Thanks in advance and thank you for playing SevTech Ages!
