### ISSUE TITLE
3.0.5 Geolosys Block lag

### ISSUE THREAD

**Issue by OldManCraft** [DarkPacks/SevTech-Ages#1559]
The Block lag on my servers has got bad after 3.0.5 update. This is only on Geolosys ores. I have updated the mod dev as they already have a issue opened on it.

**Comment by Darkosto** [comment]
Just on a server? Anything in single player at all?

**Comment by OldManCraft** [comment]
just server that I know. Not sure on single.  You can be mining the ore with lag then turn to stone and it is fine, turn back to ore and block lag is still there.

**Comment by AquaXV** [comment]
Can confirm (Also on server). I have not noticed lag on Hematite though, only all other ores.

To add to this; when switching tools during the "lag" the block will not break at all until switching back to the pickaxe.

**Comment by AquaXV** [comment]
When updating to 3.0.6 and using tinker tools the lag is no more, will check if vanilla tools still have lag and report back here.

**Comment by AquaXV** [comment]
Coal, Casserite, and Azurite no longer seem to have the blocklag issue.

**Comment by tiwuno** [comment]
After further testing, it seems to be an issue only related to the current age. I.e. coal, tin, and copper lag in Age 1 but not Age 2. iron and lapis lag in Age 2 but not Age 3, etc.

**Comment by milcondoin** [comment]
@tiwuno Could it be, that SevTech has a hook on the new ore of the age to trigger the correct advancement, just removing it on age-advancing? So each broken ore will try to trigger the advancement.

Maybe (just an idea) this trigger needs to be removed properly (like it is done on age advancement) after unlocking, so that it just becomes another already known ore.

I don't know the implementation, but it could be, that the trigger can only be removed safely, if every player on this server has completed that stage already. Depends on if the trigger lies in the player action (=> disable individually for player) or in the ore breaking (=> check if the player has already done the advancement).

Maybe currently it only checks the age number, so this could result in the problem, 9-tupling it with a hammer compared to a simple pickaxe. Not to even begin talking about vein mining with the excavator modifier.

**Comment by Xolzec** [comment]
I'm on version 3.0.6 and on Age 3. Mining hematite still lags so it doesn't seem to be related to the age, at least not in my case.

I also noticed that sometimes when you break a cluster of ore with the hammer, only the middle block gets mined (with lag) and the rest won't. If I then place cobble in the hole and mine again, everything works fine without any lag at all.

Out of curiosity I also ran the "/debug start" command on the server and here are the messages I get when the lag happens:

[Server thread/WARN] Something's taking too long! 'root.save' took aprox 139.615114 ms
[Server thread/WARN] [net.minecraft.profiler.Profiler]: Something's taking too long! 'root' took aprox 151.668431 ms

**Comment by justinrusso** [comment]
It seems as though this issue has not been happening lately. Many updates have happened since this was reported so maybe it was fixed over time. Please submit a new issue referencing this one if issues persist.

**Comment by SharkWipf** [comment]
I'm still experiencing this issue on the current SevTech build (3.0.8), mining I believe any of the Geolosys ores still heavily blocklags in multiplayer.  Can confirm on Casserite and Azurite, the only ores we've tried mining so far since entering Age 3, but we've had the problem on pretty much all ores since Age 1.

**Comment by Tahakk** [comment]
Don't use old closed issues. 
BTW. this mod got updated and I would guess will be part of 3.1.0 update ;)
