### ISSUE TITLE
Small polite request: Please make water bottles be available in the same age as Rustic brewing.

### ISSUE THREAD

**Issue by rockdemon696** [DarkPacks/SevTech-Ages#1648]
## Issue / Bug
I drank myself to Inebreation III, which causes several ill effects, on Wildberry Wine in age 2 and Inebriation can only be reduced with Water Bottles which are locked until age ?.

## Expected Behavior
Make booze, drink booze for fun, try to drink water to counter act the effects of being a drunken Viking and make the nausea go away!

## Possible Solution
Make Water Bottles accessible earlier or make a different way to drink water, such as out of a Bucket or a Fluid Bladder.

## Steps to Reproduce (for bugs)
1. Drink yourself stupid (Inebriation III or above)
2. Try to make Water Bottles to drink from to sober up... and they fall out of your hotbar due to being locked.

## Context
I drank 8 bottles of wine and I now have over 8 minutes of nausea and am stuck in a hole trying to wait it out.

## Logs
Not applicable

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8.25
* Launcher Used: Twitch

* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: No
* Optifine Installed?: No

P.S. In all seriousness this problem is kind of funny and could probably be left in as a lesson not to drink in excess even in a video game. That said more than a minute or two of Minecraft nausea is also cruel and unusual punishment.

**Comment by rockdemon696** [comment]
A better suggestion might be to stage brewing in the same stage as potions, good brews are quite powerful. A 0.63 quality Mead gave me ~30 seconds each of Wither Ward at 8 bottles a barrel that is quit a bit of Wither Protection as long as you don't down it all in one go and get too much Inebriation.

**Comment by WheresMyMtnDew** [comment]
I agree that this should be staged better- It is very frustrating because there are currently no milestones that address any aspect of this mod- I am in stage 2, not being able to remove the bad booze from bottles is wasteful and there should also be a recipe to empty to bottles by placing the full bottles in a crafting grid. Perhaps the water bottles are locked to prevent the start of alchemy? If that is the case then the brewing should be staged later... but I personally feel that alchemy should come after brewing as far as stages go- so I think it should stay in stage 2. Water bottles need unlocked, and the recipe to remove the liquids from the bottles should also be put back in.

**Comment by Alyenbird** [comment]
You can empty your bottles without drinking them by using the barrels from Primalcore. I pop a booze into the barrel, break the barrel, Behold! No more booze and my bottle is back. Just one problem. At the very top level of brew quality, the barrels stop letting you add booze. Which was super annoying because I made a huge batch of Quality 1.0 Wildberry Wine planning to store it in a barrel and couldn't.
