### ISSUE TITLE
CarryOn dupe

### ISSUE THREAD

**Issue by MCChiter** [DarkPacks/SevTech-Ages#1821]
If you put breeding harness onto a cow and then shift-rclick it to pick up ass usual, you'll pick entity up AND cause the harness to fall off, resulting in a dupe (Cow keeps breeding harness) Not particularly useful in any way, just weird. From long enough distance you can pick the harness off without the dupe.

**Comment by LadyRyl** [comment]
This happens with sheep as well.

**Comment by artdude543** [comment]
This won't be fixed due to how complex the issue is and the mods involved. BWM won't add a check to see if the player is trying to use CarryOn nor so I see a valid point to do so. As this is an interaction issue. It may be fixed later down the line. But for now, it's not something major on our to-do list.
