### ISSUE TITLE
Immersive Engineering Tesselating block crash

### ISSUE THREAD

**Issue by ADKaster** [DarkPacks/SevTech-Ages#1830]
## Context

Client crash on 3.0.6

I experienced the behavior described in #1629 just before the crash

I was attempting to put down a launch pad (landing pad?) from galacticraft next to some fences and a NASA workbench, but that doesn't seem to be what caused the crash.

Below is what I actually did:

1. Break HV transformer that is charging via one HV connector and an HV relay connected to a steam turbine/alternator circuit
2. Around 10 minutes later, observe that the area where the HV wire used to be still causes damage when walked near
3. Attempt to put the HV capacitor back in the exact location it was in before
4. Break it again, without placing connectors and/or seeing phantom wires.
5. Go off and do some other stuff for about a minute
6. Crash

EDIT: Turns out the block at (61, 69, 239) referenced in the report is an MV connector unrelated to what I was talking about above. It's connected to a tiny energy input hatch from Modular Machinery

## Logs

* Client/Server Log:  Server did not crash, only reported that I dc'd
* Crash Log: Crash report: https://pastebin.com/gkVhqm4C

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.161
* Launcher Used: Twitch

* Memory Allocated: 6GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by firez037** [comment]
I have not experienced the crash but I have experience breaking a connector or relay and having it still existing despite not actually being there (damage in the area).  If I break the other point it was connected to, it goes away.

On top of this, when I log out and log in, all my wires disappear visually.  This gets annoying because I have a few spots I need to dodge wires to prevent damage.  I have lost 3 pieces of armor so far :)
