### ISSUE TITLE
Corrupted Save?

### ISSUE THREAD

**Issue by DrunkOctopus** [DarkPacks/SevTech-Ages#1946]
I'll be updating this post until my eyes bleed. Any help would be more than appreciated.
## Issue / Bug
I've been enjoying mind boggling amounts of bugs for the last 48 hours. 
Log files are attached. There seems to be a lot wrong, but I'm specifically concerned with my base crashing the server.

I think that pneumaticcraft, immersive engineering, or perhaps carmod is causing these issues.

## UPDATE:
I definitely fixed it by wiping away part of my base. Blocks included in that wipe were from: advanced reactors, actually additions, carmod, immersive engineering, pneumaticcraft, modular machinery, carmod (likely not the problem unless there was an issue with car workshops), astral sorcery, rustic, bibliocraft, elevators, chisel and bits, chisel, cyclic (mostly for power transfer), some better with mods/add-ons blocks, and a few chunk loader gadgets (likely not the problem as I only wiped a couple).
Sadly this fix did little more be besides further screw up the world. Too bad!

## Possible Cause
Vortex Tubes from Pneumatic

## Expected Behavior
Anything but this lmao

## Possible Solution
I'm using MCEdit to try and delete errored blocks

Steps to Reproduce (for bugs)
1. I wish I could retrace days of progress for multiple players

## Logs
Before McEdit
[latestB4start.log](https://github.com/Darkosto/SevTech-Ages/files/1927475/latestB4start.log)
[2018-04-17-1.log](https://github.com/Darkosto/SevTech-Ages/files/1927476/2018-04-17-1.log)
Important: https://pastebin.com/SJiemhRL
[crash-2018-04-18_19.23.50-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1927484/crash-2018-04-18_19.23.50-server.txt)

Trying to start the server after MCEdit
http://prntscr.com/j7a06c
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1927507/latest.log)
More crash reports
[crash-2018-04-19_06.38.34-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1927754/crash-2018-04-19_06.38.34-server.txt)
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1927756/latest.log)

[crash-2018-04-19_05.32.26-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1927504/crash-2018-04-19_05.32.26-server.txt)

Overall Debug Session Notes
[growls_debug_notes (1).txt](https://github.com/Darkosto/SevTech-Ages/files/1927480/growls_debug_notes.1.txt)

## Client Information

* Modpack Version: 3.0.6
* Java Version: Latest Java8
* Launcher Used: Twitch

* Memory Allocated: 8.5gb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

Server Information (I'm not the owner I just work here without access to the console)
* Java Version: Unknown
* Operating System: 
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?: Vanilla Forge

* Additional Content Installed?: No

**Comment by xXNiugaXx** [comment]
I got the same issue on my private Server, i placed down some Pneumatic Chamber Blocks and it Crashed 2 min later. As i rejoined, the Chunk loaded up kinda long and as it was loaded the Blocks wasnt anymore there and the Server Crashed again. Now everytime i rejoin it crash the Server again and again but only next to these Blocks... if someone other Join the Server and hes not Next to my Base to Load these blocks nothing happen.

If u find some Grammar failure's keep it for u ty 👯‍♂️

**Comment by desht** [comment]
This does not look like a PneumaticCraft bug:

``
[09:13:49] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=overloaded:infinite_capacitor, properties=[]}
``

In particular **Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=overloaded:infinite_capacitor, properties=[]}**

The Vortex Tube tile entity has tried to get its ``facing`` property, but the block at its location has changed to ``overloaded:infinite_capacitor``, which does not have that property.  PneumaticCraft is reporting this (fatal) error, but there's no evidence that it caused it.  It looks like something else has already corrupted the world (block and tile entity mismatch) at this point.

**Comment by DrunkOctopus** [comment]
I'm not a coder so thanks for the help @desht !! Is there any information I can provide to help make sure this doesn't happen to other players?

**Comment by desht** [comment]
It's hard to tell but it looks like you have some world corruption, possibly from an external source, e.g. file system corruption due to disk failure. I would advise checking your OS logs for anything relevant.

I also noticed some "permission denied" errors while loading chunks in one of your logs, which suggests either someone has messed up the perms in your world save folder, or again file system corruption.

**Comment by DrunkOctopus** [comment]
Thanks for the help! I'll take a look and get back to you guys
