### ISSUE TITLE
Radiation with Extra Planets

### ISSUE THREAD

**Issue by MrBirk** [DarkPacks/SevTech-Ages#1990]
I found the moon and mars both very manageable in terms of Radiation. Venus was absolute hell until I managed to get the shield controller after eating through a few sets of space suits trying to find a dungeon, thankfully the first one had it. The asteroid belt also isn't that bad.  

Mercury and beyond I feel like that rate of radiation is just crazy. I spend like 2-3 hours getting my radiation back to 50%, as it halves to 2.5% when sleeping below 50% so it's not really worth getting it to 0%, just to spend maybe 10-15 minutes planet side which isn't much time to try and find the dungeons/resources and loot them and kill the boss before having to leave to repeat this cycle. My first trip to Jupiter was very short I upgraded the suit and went back and the extra time gained from the suit upgrade felt negligible.

This is my first experience with this mod so that makes me a bit slower. I realize I can adjust the config for myself I just feel I am an average player and lot's of others may also find this portion of the mod pack frustrating.

**Comment by SphynxLoL** [comment]
You have to deal with the sleeping method until you have a Tier 5 Rocket (Saturn) since the Decontamination Unit is a waste of time and power. From there, here is a checklist :

- [ ]  Go to **Mercury** for **Infected Water and Potash**
- [ ]  Go to **Ceres** and convert Liquid Crystalized Water to **Iodized Salt** using a Basic Crystallizer.
- [ ]  Build a **Basic Purifier** and combine Infected Water + Iodized Salt to get **Clean Water Bucket**
- [ ] Build a **Basic Smasher** to smash Potash to **Potash Shards**
- [ ] Build a **Solar Evaporation Chamber** and place it in the sun with 12 Potash Shards to get **Potassium**
- [ ] Build a **Basic Chemical Chamber** and combine Iodized Salt + Potassium to get **Potassium Iodide**
- [ ] Go to **Saturn** for **Magnesium Ore**
- [ ] **Make Anti-Rad**

I recommend doing it in this order to let your radiation cool down between Ceres/Mercury and Saturn. If you are really struggling at Tier 4 you can build the Decontamination Unit. It takes a ridiculous amount of power (that can only be charged with batteries) and only cures 10% radiation. Once you hit Tier 5, I highly suggest carrying around a backpack of Anti-Rads. Only use them when you reach 95-100% to get the most out of them.

Alternatively, from what I have read, anything that provides Regen II will out heal all radiation damage. If you can deal with the annoyance of taking damage every second.

**Comment by ferrium42** [comment]
And what do you about , "your armor is gone away after 10 min" . Build this crazy shit over and over ? (item repair from AE help) For me this mod has to be balanced.  The Armor should took less damage and the radiation is way to high. Not that this mod is boring like hell, it give only modpack creator a way to hide things behind hours of crafting and searching dungeons (how to find it bevor this expensive armor break?)  to build rocket after rocket ....

**Comment by SphynxLoL** [comment]
@ferrium42 The shield controller (found on Venus) is available when you have a T3 Rocket. Found in dungeons, it will protect armor from ALL types of damage.

I do agree Extra Planets is bland and repetitive. I am not really a fan of being forced to do it as I was with twilight forest to progress. I to wish that twilight forest was streched across the pack instead of just a single age. Just my opinion. I can only take so much "exploration" in one sitting. With Extra Planets, fighting radiation and running around with your head cut off looking for a dungeon... 6+ times is quite annoying. If dungeons were A LOT easier to locate and find, the mod would be enjoyable but in its current state every planet is just a copy pasta from the last.
