### ISSUE TITLE
Lava crystal gets eaten inside ie alloy kilns

### ISSUE THREAD

**Issue by Frunblumglin** [DarkPacks/SevTech-Ages#2033]
## Issue / Bug
if you place a lava crystal inside the alloy kiln as a fuel source, the alloy kiln eats the lava crystal instead of behaving like the lava crystal should and draining lp.

## Expected Behavior
When placing a lava crystal inside a fuel source it should drain 50lp and register it as 1 coal's worth of fuel, as stated in the blood magic's sanguine scientiem.
![image](https://user-images.githubusercontent.com/13581892/39109113-546f154e-4680-11e8-82ba-b433619b4da3.png)
![image](https://user-images.githubusercontent.com/13581892/39109131-642f7a82-4680-11e8-896d-82c6b4480307.png)
![image](https://user-images.githubusercontent.com/13581892/39109152-75c4c57c-4680-11e8-9fdb-375981c60883.png)

## Possible Solution
i have no idea how to solve it... i just know how it's supposed to work D=

## Steps to Reproduce
1. Place lava crystal in fuel slot in alloy kiln
2. Add in valid alloyable metals
3. watch lava crystal get eaten D=

## Client Information
![image](https://user-images.githubusercontent.com/13581892/39109248-e0d3a43c-4680-11e8-9241-ea00a8e5e772.png)
* Modpack Version: 3.0.6
* Java Version: see image
* Launcher Used: twitch launcher
* Memory Allocated: see image
* Server/LAN/Single Player: single player
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Frunblumglin** [comment]
yes i did right click the crystal to bind it to my network btw.

**Comment by Frunblumglin** [comment]
just confirmed this is also an issue with the simple combustion generator, and you can't use a lava crystal inside the RFtools coal generator either.

**Comment by artdude543** [comment]
This seems to be a BloodMagic issue have you tried reporting it to their tracker and/or looking for issues already on there?

I'll test this on the latest version now for the next pack update to see if the issue persists, however.

**Comment by artdude543** [comment]
Yeah, this is still an issue on the latest update (2.2.10-93)

**Comment by WayofTime** [comment]
Just to confirm, all of those listed generators consume the lava crystal? I think the RFTools coal generator is hard-coded to only use coal, so that makes sense.

**Comment by WayofTime** [comment]
From my studies:
Simple Combustion Generator eats Lava Buckets, so they have an issue.
Fuelwood Heater eats Lava Buckets, so they also have an issue.
And finally, Immersive Engineering's kiln consumes Lava Buckets.

By consume, I mean it eats the lava bucket without returning an empty bucket. So it's actually not an issue with my mod, but an issue with all of their mods that was only found because of the lava crystal.

**Comment by artdude543** [comment]
Okay cool, thanks for looking into it Way though much appreciated!

@Frunblumglin if you want to report the issue to the other mod developers and tag back to this one your more than welcome for this issue to go further. Make sure you follow their requiements for logging reports however!

**Comment by WayofTime** [comment]
Yeah, so I can give a bit more insight as to what is occuring, mainly for the other mod developers that are wondering how to fix their issue (honestly they probably know what the issue is, but I do want to outline it anyway).

When they are consuming the item, if it is the last item that was consumed they need to see what the contained item is. In the case of the lava bucket, it contains an empty bucket. For some reason the existing checks that they have do not work, therefore instead of an empty bucket they get nothing. Maybe they are getting an empty bucket with a stacksize of 0? Not sure. Best way to debug it would be to look at how the vanilla furnace consumes its fuel and replicate it.

The Lava Crystal is just a glorified lava bucket - it returns itself when consumed, and during the fuel check will consume LP from the network. It works off of the honour system - I am assuming the mod using the crystal will only check what fuel it has when it needs fuel, and only check it once. Thankfully hasn't been too bad of an issue thus far!
