### ISSUE TITLE
[3.0.6] Request for recipe for Blood Magic Crystal Cluster

### ISSUE THREAD

**Issue by RyanP1991** [DarkPacks/SevTech-Ages#2112]
Suggestion:

I would like to make a suggestion for a recipe for the Blood Magic crystal cluster to be added so it would be possible to make a Tier 6 altar and blood orb.

**Comment by JRiebling** [comment]
This is a Blood Magic issue. The old crystal clusters from 1.7.10 were removed a while ago. There are new demon will crystal clusters, which are currently bugged and addressed [here](https://github.com/WayofTime/BloodMagic/issues/1252). Whether that will actually allow us to make a T6 altar, I don't know.

Out of curiosity, what are you doing that you need a T6?

**Comment by Cosido** [comment]
I'm unaware of a bug with the clusters, from what I get from that article is that it was addressed however. But Myself as well as a friend have tested the capabilities of a T6 Altar. There is not a way to obtain the clusters legitimately as the demon invasion isn't implemented. But a T6 Altar, (Level, Extra Runes, Extra Orb) are implemented and work if you could obtain those cluster blocks. I would love the extra tier, and if we can just go around waiting for an update, and create a custom recipe in one of the advanced crafting tables?
Mabye a diamond crafting table, with a beacon as a center-piece due to it being needed for the previous tier blood altar.

Just a suggestion, Thanks for the time!
