### ISSUE TITLE
Overcoming Random numbers - Darklands, Rock Crystal Ore, Celestial Altar starlight

### ISSUE THREAD

**Issue by CDArena** [DarkPacks/SevTech-Ages#2114]
## Issue / Bug
This is more of an Issue than a bug - the possible difficulty of finding enough starlight to enter Age 3. 
My search for starlight is documented here: https://imgur.com/a/Muieyjs
As a programmer I know that random numbers can be tricky; working with other APIs by other authors even more so. In this mod pack I ran into numerous issues that can be attributed to "unluckiness" but I tried to do as much as possible in a legit manner. 

My first fight with random numbers was struggling to find darklands - I didn't realize you can head North and eventually run into them - I somehow overlooked this nugget of information. My first base was very far south, and it took me a while to find a satisfactory area to move to.

My second struggle Next I struggled to find the Rock Crystal Ore - finally lucking onto some underwater when I swam over to a nearby island. (Look for "spiky" rocks on the surface - see Celestial Crystal Cluster in NEI to see roughly what they look like)

My third issue was upgrading from Luminous Crafting table to Starlight Crafting table to Celestial Altar. Each upgrade required more starlight, and a farther trip from my base. My search for starlight is documented here: https://imgur.com/a/Muieyjs  But basically each time I upgraded, the starlight at the current location wasn't enough for the upgraded altar and the Celestial Altar was ridiculous - Even though I finally found a spot that light up the meter, it wasn't enough and I had to pillar up to Y=129. The Fosic Resonator is critical here.

I don't want to put off the mod author because the pack is excellent and I can tell a lot of work went into it - far more than the majority of other Minecraft Mod packs . it looks like many of the issues I ran into were addressed with subtle clues in the quest book, which I applaud.  This starlight issue was a royal pain for me though - if the Fosic Resonator had a strength meter of some type, or perhaps if the amount of starlight for a critical recipe like the Coal Engine was lowered a bit, maybe it could improve the game experience for other folks who had back luck like myself.  I've seen several play-throughs where they got lucky with Astral locations, so it seems to just be "bad luck" for me.

And I haven't had any more crashes since forcing the Twitch launcher to upgrade it's version of Java, so perhaps some guidance for that can be added to the overview (One of the other Issues had a Google Docs link that I used).

**Comment by lawl281** [comment]
There is no need to travel for astral sorcery. Through other upgrades as mentioned by Targren you can actually get enough light without traveling to the power areas.  Those places you find with fosic resonator just make it significantly easier.

**Comment by CDArena** [comment]
Silly me for following the quest book's suggestion and side quests - should have just explored the whole mod!

**Comment by CDArena** [comment]
Mmmm - also, making the Linking tool requires... a crapton of starlight again. So yet another trip to the remote pillar is needed.

**Comment by gattsuru** [comment]
For anyone else having this problem, Spectral Relays (in their multiblocks, fitted with "Glass Lens" items) will lend power to a nearby Astral Sorcery crafting table without the use of the Linking Tool.  If it's close enough, the particle effects will flow toward the direction of the nearby table.  You'll eventually want this infrastructure anyway -- even max-strength starfield at y=125+ at midnight won't give enough starlight to make a collector crystal unaided, and may struggle to make an attunement altar -- and the Spectral Relays can be crafted with nearly no starlight on the base-level altar. 

If you're in a very low starlight area and at ground-level you may need to make many Relays, Lens blocks, and the Linking Tool for the Coal Engine, Attunement Altar, and Irridescent Altar.  Because Spectral Relays too close to each other reduce their starlight bonus, this usually is the sort of situation where it's easier to relocate, but it should be possible anywhere with access to the sky.  The Hunting Dimension can also be useful, as it is always midnight there and isn't likely to have you at nadir of starlight in both dimensions.

**Comment by artdude543** [comment]
Going to close this one as it seems resolved. And if more discussion is needed please use our Discord. I'll get the post to link it 🙂
