### ISSUE TITLE
Diamond dupe

### ISSUE THREAD

**Issue by predakanga** [DarkPacks/SevTech-Ages#2156]
## Issue / Bug
Diamonds are dupeable in age 5 (material cost: 1 cobblestone per diamond, plus some energy and starlight)

## Expected Behavior
Diamonds should be craftable (i.e. pneumaticraft compression), but not out of fewer diamonds

## Possible Solution
Tweak the Mekanism Combiner Diamond Ore recipe to use 4 diamond dust instead of 3

## Steps to Reproduce (for bugs)
1. Create an Astral Sorcery Starlight Infuser
2. Create a Crusher from Immersive Engineering, Mekanism or Actually Additions (Diamond -> Dust)
3. Create a Mekanism Combiner
4. Obtain 3 diamonds by your preferred means
5. Crush 3 diamonds into dust
6. Use Combiner with 3 diamond dust and a cobblestone to create one diamond ore
7. Use Starlight Infusion to convert one diamond ore into 4 diamonds
8. goto 5

## Client Information
* Modpack Version: 3.0.6

**Comment by justinrusso** [comment]
Do these recipes really even need to be kept?

**Comment by predakanga** [comment]
The Diamond Ore recipe is handy for creating the Orion Drive.

You could certainly remove the Diamond Ore->4 Diamonds Starlight Infusion recipe; it's best in class for processing, but I'm sure people could cope.

**Comment by TomeWyrm** [comment]
I'm more of a fan of the first suggestion. Make the ore require 4 dusts to make. Because there are many reasons one might wish to craft ores rather than find them. Decoration, crafting recipes, auto-processing making the other two annoying... probably a dozen others I can't recall.

But I'm always a fan of leaving in functionality and fixing exploits in as unobtrusive/light-touch/conservative a method as can be managed. Especially in a sandbox game.

**Comment by syrun97** [comment]
#2225 this exploit works on coal and quartz too. just use mechanical sqeezer(from intergrated dynamics), and enrichment chamber instead

**Comment by Stifling-Bossness** [comment]
This still seems to exist in 3.0.7: https://imgur.com/a/e92JERl
