### ISSUE TITLE
crash while loading jupiter dungeons

### ISSUE THREAD

**Issue by Frunblumglin** [DarkPacks/SevTech-Ages#2175]
## Issue / Bug
Loading in jupiter's dungeon caused a crash in 3.0.6... looks like it's specifically the boss spawner block in this case. Reloading in the save and putting it into a fresh install of the game didn't fix anything... gonna try and figure out how to reset my character without losing my inventory if possible.

## Logs
* Crash Log: https://pastebin.com/RL0raUm4

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_171 (64 bit)
* Launcher Used: twitch
* Memory Allocated: 12gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by MJRLegends** [comment]
@Frunblumglin Sorry for the long delay, but was you able to reproduce this on other worlds, and was this the first dungeon you saw/went to on Jupiter? cc @justinrusso

**Comment by MJRLegends** [comment]
I believe this to just be a bad seed, and causing the dungeon generator to not generate the dungeon correctly

**Comment by MJRLegends** [comment]
I will make a pull request for GC to add a null check so the dungeon wont crash the world out but will just spawn messed up

**Comment by MJRLegends** [comment]
Ok so i can confirm i have tested with a null checker on the line crashing and it works and confirms my idea of the dungeon just not generating correctly 
![2018-05-11_19 03 24](https://user-images.githubusercontent.com/8526321/39939411-1fd49a52-554e-11e8-96b8-25c5ab226193.png)

I have made a pull request to fix this over at here on the GC side of things https://github.com/micdoodle8/Galacticraft/pull/3394

Im going to close the ExtraPlanets issue since its not needed now that we have found the issue and resolved it hopefully if the pull request is accepted which i cant see why it wouldnt be

cc @justinrusso
