### ISSUE TITLE
Geolosys samples but no veins in Abyssalcraft dimensions

### ISSUE THREAD

**Issue by MrHrulgin** [DarkPacks/SevTech-Ages#2184]
## Issue / Bug
In the Abyssal Wastelands (and I assume, but have not verified other Abyssalcraft dimensions), there are samples on the surface, but veins don't spawn in the stone below. As of issue #722 the abyssalcraft stone types weren't on the whitelist for generation, so that's probably the issue here.

## Expected Behavior
I would expect that if there are samples spawning, that the veins would as well. 

## Possible Solution
Either blacklist the abyssalcraft dimensions from geolosys ore spawning or whitelist the abyssalcraft raw stone types for vein spawning (preferred). 

## Steps to Reproduce (for bugs)
Go to The Abyssal Wasteland.
Find surface samples.
Fail to find veins.

## Context
Not super important. There's plenty of other, safer places to mine. But it's also a pretty easy fix.

**Comment by Jandakast** [comment]
Please provide a screenshot of your pipe setup. I cannot reproduce this in Dev.

**Comment by Jandakast** [comment]
>_< To many tabs open. Will check this in dev.

**Comment by Jandakast** [comment]
Unfortunately this is an issue with custom ores made in Geolosys. There is currently no way to blacklist the custom ores in dimensions. We can only control what blocks the ore veins can spawn in. Since the samples spawn on the surface and don't actually replace any blocks we cannot stop them from spawning. There is a Feature Request for the mod to add this functionality. I will discuss allowing the veins to spawn in the abysalcraft stones with the team. 

https://github.com/oitsjustjose/Geolosys/issues/62
