### ISSUE TITLE
i have added optifine and i have a black screen with atlauncher 

### ISSUE THREAD

**Issue by Minehors** [DarkPacks/SevTech-Ages#2284]
i have added optifine and i have a black screen with atlauncher and launch mc (blackscreen) and then close it immediately because its an error srry for bad ENG pleease can u help me

**Comment by artdude543** [comment]
If your trying to use ATLauncher for 3.0.7 it won't work due to an issue on their side. Please use Twitch Launcher or MultiMC for the time being.

_Commence Canned Response:_

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
