### ISSUE TITLE
Can not install after clean download.

### ISSUE THREAD

**Issue by GiGDDragon** [DarkPacks/SevTech-Ages#2292]
Download 3.0.7 server files extract them to a new folder and then click install and nothing happens. No logs generate. can install forge manually but can not start server or install the server.

**Comment by artdude543** [comment]
The files were tested before release. Make sure you are running the correct type of file for your system. I.E. batch for Windows and Shell for Linux.

But these do work fine as it was confirmed by 10 other users in my testing group. So your doing something wrong here. Also, make sure if your upgrading that you copy the settings file as values inside of that change when we update forge. So that props your issue here that your settings file is out of date.
