### ISSUE TITLE
game crash when building terrain after update(3.0.7)

### ISSUE THREAD

**Issue by Hotrod79** [DarkPacks/SevTech-Ages#2308]
## Issue / Bug
games crash while loading world entity colliding with object??

## Expected Behavior
expect to load saved game

## Possible Solution
??

## Steps to Reproduce (for bugs)
1. repeats ever start
2. click on world start and the terrain loading screen starts and as soon as it shows 0% it immediately crashes.

## Context
just updated to newest version, 3.0.7. had no issues with previous versions. started game, loaded and as soon as i clicked on the svaed world the game crashed at 0% loaded.

## Logs

* Crash Log: https://pastebin.com/embed_js/MmbrY89w

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 update 171
* Launcher Used: 2.0.1049

* Memory Allocated:

* Single Player:
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by artdude543** [comment]
Your missing mods due to the current bug with the Twitch Launcher. If you did not back your world up you've lost it forever.

Until Twitch works out the issue we can't do anything on the pack side of things. You'll have to keep trying to ensure the download you have contains all the mods for the pack before your world will load fine again.
