### ISSUE TITLE
Crashing every few minutes , astral sorcery crash loop it seems

### ISSUE THREAD

**Issue by Chlev** [DarkPacks/SevTech-Ages#2356]
## Issue / Bug
Pack keeps on crashing few minutes into entering the world

## Expected Behavior
N/A
## Possible Solution
as far as i can tell from the logs , astral sorcery keeps crashing the pack somehow

## Steps to Reproduce (for bugs)
hard to reproduce as it started happening all of a sudden without me changing anything

## Context
N/A

## Logs
* Client/Server Log: 
* Crash Log: https://pastebin.com/XsKmS5s3

## Client Information
* Modpack Version:3.0.7
* Java Version:1.8.0.171
* Launcher Used:Twitch Launcher
* Memory Allocated:7GB
* Server/LAN/Single Player:
* Resourcepack Enabled?:yes , Faithful 32
* Optifine Installed?:no

**Comment by justinrusso** [comment]
What dimension are you loading in to?

**Comment by Chlev** [comment]
doesn't matter which dimension.removed attunement altar,and focus lenses.no crashes so far. to me it seems it has something to do with constelations and attunement altar but i may be wrong

**Comment by Giovanni-NL** [comment]
FWIW, we are getting the same crash on our server, on seemingly random moments. We can play without problem for a while and then the server crashes with this error:  https://pastebin.com/NjntT7nU 
Restarting the server then gets the world back on-line, and then after a random amount of time (did not time exactly, but certainly more than 30 minutes) the same crash happens again.  For us, it all started when we placed some Celestial Gateways in the overworld and on the moon.  Crashes happen in whatever dimension we are at that time, so that does not seem to be related to the crash happening.

Pack used: SevTech Ages version 3.0.7
Astral Sorcery:  astralsorcery-1.12.2-1.8.10.jar

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄
