### ISSUE TITLE
Low TPS/Server Lag with greater than 2 clients connected.

### ISSUE THREAD

**Issue by commgdog** [DarkPacks/SevTech-Ages#2378]
I have set up a server on 3.0.7 for me and around 5 friends and we seem to be running into some server performance drops when more than 2 clients are connected to the server.

We aren't that progressed, all but one of are in age 1. The performance drop occurs even when nobody is exploring.

When the server is rebooted, the lag goes away for about 10 minutes, then returns.

I don't see anything in the log files related to the issue. I installed a server profiler mod and see that the TPS drops down to around ~8.

I checked the server itself and it seems to be pegging one core to 100%.

Is there any settings I should be tweak to fix the high CPU usage?

Note: Client performance is not an issue.

```
1Gbps connection
24 x Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz (2 Sockets)
128GB ram
MC server is on a tmpfs ramdisk
```

```
# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
# uname -r
4.9.0-5-amd64
```
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
```
forge-1.12.2-14.23.3.2679-installer.jar
forge-1.12.2-14.23.3.2679-universal.jar
```
```
-server
-Xms8G
-Xmx8G
-XX:+UseG1GC
-Dsun.rmi.dgc.server.gcInterval=2147483646
-XX:+UnlockExperimentalVMOptions
-XX:G1NewSizePercent=20
-XX:G1ReservePercent=20
-XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=32M
```

**Comment by artdude543** [comment]
2.1 GHz is really low for a modded server. Vanilla you could get away with along with lightweight packs. But this pack is hard bearing for both clients and servers due to the chunk generation and rendering. Ideally, you'd want something more powerful.

But pre-generating the terrain could help. The recommended method is to the use the forge gen command which you can find details [here](https://github.com/DarkPacks/SevTech-Ages/wiki/Pre-Generate-Command). But other than that I'd expect to see lag/ticking issues with this modpack and that sever spec.
