### ISSUE TITLE
Server Problem: Connection Lost- Time Out

### ISSUE THREAD

**Issue by Metapalms** [DarkPacks/SevTech-Ages#2396]
* Server/LAN/Single Player:  Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: Java 8
* Operating System: 
* Hoster/Hosting Soultion: minecraft-hosting.pro
* Sponge (Non-Vanilla Forge) Server?:

Log:
https://pastebin.com/WASpfFG5

Whenever my friend tried to join the server I had set up in the consol I had always gotten this error so matter what and on his end he always got a different message. I am currently at his house and have tried everything seeing if it was just something on his end. I even ran back over to my house and installed my ATLauncher files on an external hard drive only to come back thinking something had not downloaded correct. I do not know what to do now. The server works perfectly fine from my house it is just when I am here it does not connect.

**Comment by Cntrldfusion** [comment]
What are the messages that he is getting?  Are they several different "netty.io" type messages?  If so is he using a wireless connection?

**Comment by artdude543** [comment]
This is an environment issue. If you're running a server from home, ensure the ports are forwarded correctly and that they are open. Along with ensuring that the server is even loading correctly and binding to the port. _(Sometimes MC will see the server even tho it's not configured correctly)_ 

Running a local server from home is always going to lead to issues as you have to factor in your own home usage on the network, external ISPs _(some block game ports)_ along with the jitter time. Which would cause a similar issue with the timing out.

All I can suggest is double check the port/forwarding and/or your router set up _(if your connecting via your external IP)_ If your using something like Hamachi or similar I won't give support on that front due to personal thoughts on those systems.

But it sounds more like a setup issue. So follow the steps mentioned above. If you still get now where the MC forums have a tonne of support/help/suggestions for home servers. But we are not here to give a crash course on setting/managing servers.
