### ISSUE TITLE
Crash when breaking Advanced Coke Oven

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#2442]
## Issue / Bug
I tried to break an advanced coke oven because it was facing the wrong way, and my game crashed as soon as I broke a block.

## Steps to Reproduce (for bugs)
1. Build Advanced Coke Oven (without the preheaters)
2. Whack the central coke brick with an engineer's hammer to form the multiblock.
3. Attempt to break a block from it.

## Context
I'm in need of a lot more steel to build a moon base, and I needed a lot more coal coke for the steel. I was hoping to use the advanced coke oven with preheaters instead of wasting more space building multiple standard ovens.

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/d1d40bd1c49daac6b1f938b22ac35792
* Crash Log: https://gist.github.com/Stifling-Bossness/0f95fb6662e4be939f2998d8678f3747

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.172
* Launcher Used: Twitch 7.5.6702.487
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, 32x Faithful Modded Edition
* Optifine Installed?: No

**Comment by Stifling-Bossness** [comment]
Yes, I no longer crash when I break the advanced coke oven. I rebuilt and broke it multiple times to make sure.

**Comment by madkat5** [comment]
I don't know if this is related - I'm getting a NullPointer Exception immediately on world load due to something in Immersive Tech, which I left a message in their GitHub even after manually updating to 1.3.9.  My game will load if I disable ImmersiveTech and let minecraft delete all ImmersiveTech blocks - though that removes all of my power generation so I'd rather not go that route.
