### ISSUE TITLE
Client Back To Title Screen

### ISSUE THREAD

**Issue by Coltphyton** [DarkPacks/SevTech-Ages#2465]
1.Start launcher
2.loading screen
3.done!
4.Select world
5.loading
6.freeze...(don`t load longer)

At first time crating a world , it works.But when i create an other one or I try to open the other world again , it will not open it or create it... :(
Context
Im sad becouse i want to play it with friends and i rlly like this pack....i tryed everything....i searched many reports with the same topic here.I tryed to toggle mods off and on and change settings....nothing work.
Logs

    Client/Server Log:  https://gist.githubusercontent.com/Coltphyton/7d8d606219af7b308b381dfc5d13b586/raw/85c35b7776d788b140c24df2d944e15385e68abb/crash
    Crash Log:  https://gist.githubusercontent.com/Coltphyton/7d8d606219af7b308b381dfc5d13b586/raw/85c35b7776d788b140c24df2d944e15385e68abb/crash

Client Information

    Modpack Version:3.0.7
    Java Version: 10 1.8.0_171
    Launcher Used:Curse (twitch) AtLauncher too

    Memory Allocated:6GB

    Server/LAN/Single Player:Single Player
    Resourcepack Enabled?:No
    Optifine Installed?:No

**Comment by Coltphyton** [comment]
i found this log so:
1.open ATlauncher
2.took SevTech ages and click on *open folder*
3.then i click on logs
4.and now i copy the file *latest*

there ist any folder named *crash-report*

**Comment by artdude543** [comment]
Firstly don't be an ass when you get told to do something. You can't call something a "crash" when you don't have crash logs to prove it.

Simple fix for this is to not use anything from Improved Backpacks as that's causing the issue here. _(Like if you read the report correctly)_ that mod is a nightmare to get anything fixed. So this won't be a quick thing something inside a backpack is causing the issue.

**Comment by Coltphyton** [comment]
yeah ok...im sorry. But i cant do anything to help with your manuel.....I just see many errors and then i think :ok thats to much for me....sorry....i wait for the next update then.....

**Comment by Jandakast** [comment]
Have you tried to download the pack to a new instance?
Are you able to give the Pack 8GB of RAM?
Try disabling/deleting Fancy Block Particles and Better Foliage mods.

**Comment by Coltphyton** [comment]
yeah i can give 8GB ram but i just have 16GB.....anyone sad´s that is maybe an bug-issue to give the half of your ram to the game      (ikr best englisch...)And yes i reinstalled the pack 4th times....but i try to disable the mod now...

**Comment by Coltphyton** [comment]
nope...dont work

**Comment by Coltphyton** [comment]
i dont know....all my friends are able to run the pack...only me.And i reinstalled the pack 4th times and i created around 10 worlds....everytime these backpacks? rlly? thats badluck

**Comment by artdude543** [comment]
It won't be just the backpacks. There is something else going on. But as you stated you don't have crash logs. If the crash is crashing like your saying you **will** have the folder and the logs for them. It's standard and has been since Minecraft was born.

Without the reports, we can't help you anymore. As the logs, you provided only tell us like 5% of what's going on. They are pretty much useless to us.

**Comment by Coltphyton** [comment]
i just have this log , an log from better foliage (debug) and an log whilst starting the pack , an main/debug log....and i have an log named *error* in the caliper folder....

**Comment by Coltphyton** [comment]
oh!!! i found the issue.....it was rlly the better foliage mod....but i got this mod 2 times in my folder...i deleted one and the other one still starts...cuz that my game still freeze...but now the sad there are missing blocks..i accepted and it works ;)   props to you dude! You helped me much :)
