### ISSUE TITLE
IE HV transformer unconnects wires

### ISSUE THREAD

**Issue by loydan** [DarkPacks/SevTech-Ages#2469]
## Issue / Bug

Immersive engineering's HV transformer unconnects wires of itself after i unload chunk it is in. At first i thought wires got burn cuz of too much current but after i log out and log in i saw wires on the ground. So the block doesnt connect wires after it loads in the world.
## Steps to Reproduce (for bugs)

1. Place HV transformer, connect it both sides with wires, log out.
2. Login

## Logs

* Client/Server Log: https://gist.github.com/loydan/c0aaa11bd5e14e93c409df0fb6fb27b9
* Crash Log: no crash

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 Update 171 build 1.8.0_171-b11
* Launcher Used: Twitch, Jar-launcher
 
* Memory Allocated: 12 288 mb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by loydan** [comment]
![image](https://user-images.githubusercontent.com/39320724/40092254-089b433e-58c5-11e8-94d2-de9bd5b2d659.png)
And after relog
![image](https://user-images.githubusercontent.com/39320724/40092477-23a7e14a-58c6-11e8-80af-0b56f962e4c6.png)

**Comment by artdude543** [comment]
Is power still being transferred? Or does this break the transfer? As it could be there but not rendering.

**Comment by Stifling-Bossness** [comment]
I've had the same issue, and I also thought it was burning it the wires. In my experience, the wires did not continue to transfer power.

**Comment by dalsio** [comment]
I can also confirm this, but strangely for me only the MV wire I have connecting it to the LV Transformer detaches. I can also confirm that no power is transferred because my entire power production also stops when unloaded (water/oil pumpjack into boiler/turbine/alternator) and I have to attach a new MV wire before I can send power back from a capacitor into the system to jump-start it again. I can also confirm that setting up a chunk loader (the weirding machine) seems to solve this issue (the wire problem). My exact setup has a HV and LV transformer jammed right next to each other, taking HV line from a relay, MV line between transformers, and a LV line out to HV capacitor. 3.0.7, Java 1.8.171, Twitch launcher.

**Comment by loydan** [comment]
Up

**Comment by loydan** [comment]
Will status of this ticket ever be renewed?

**Comment by artdude543** [comment]
Is it open no? So it's still being looked into. Have patience we all have lives and jobs this is a hobby...

**Comment by loydan** [comment]
Yes, i know, just being worried status hasnt been updated for a week after the post. Sorry

**Comment by artdude543** [comment]
Thanks! Could I be cheeky and ask when we could see this on CF? 🤗

**Comment by malte0811** [comment]
I'm the wrong person to be cheeky to for that, Blu decides when a new CF build goes out (and he generally does not like ETA requests).
One request from my side: If you aren't going to report these issues to the mods, maybe at least ping the author(s)?

**Comment by artdude543** [comment]
Yeah, I would normally do that but was waiting on feedback from the OP.

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄
