### ISSUE TITLE
[3.0.7] chopping blocks not stackable in advanced stump

### ISSUE THREAD

**Issue by BiZZKeryear** [DarkPacks/SevTech-Ages#2558]
Since they break easily and are hard to fill ... I wanted to make a bunch of Work Stumps MK.2 on a  Work Stump MK.2
I filled in 5 of everything ... but it didn't let me do it for the chopping block. In my inventory I can do that just fine, though (using several chopping blocks, to create several Work Stumps [MK1])

**Comment by artdude543** [comment]
This is intentional they are not meant to be stackable nor will ever be.

**Comment by gonfuckyourself** [comment]
@artdude543
Ooook, I (BiZZKeryear) only opened the topic because it does stack anywhere else. It stacks in inventory and in inventory crafting.
If the not stacking is by design, then it shouldn't stack anywhere. (Or it should also stack in the Work Stump ***MK.2*** )


## Offtopic
@justinrusso @Jandakast We can play this game all day long. And you haven't seen me spam,yet. If you really wan't me to, I can flood fill this section of the net. And trust me I can make accounts as fast you you can block them.
@Jandakast And https://github.com/DarkPacks/SevTech-Ages/issues/2556 isn't a duplicate of https://github.com/DarkPacks/SevTech-Ages/issues/1812 It's separate issue since it expresses differtently but for that you would need to able to read ...
Even if both are based on the same issue then the right move would be a merge.
