### ISSUE TITLE
[3.0.7] [PneumaticCraft: Repressurized] [Cosmetic] Bullets have two recipes, one of which requires nothing

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2571]
## Issue / Bug
There's a recipe for bullets that requires no items (of course it can't be crafted). Entirely cosmetic. Somewhat comical.

![2018-05-21_01 10 25](https://user-images.githubusercontent.com/1721589/40340608-825e0baa-5d45-11e8-8310-7b5709c23851.png)

## Expected Behavior
The recipe requires items or doesn't exist at all.

## Possible Solution
Probably scripting. Might have something to do with recipes for adding potion effects.

## Steps to Reproduce (for bugs)
1. Check JEI recipe for PnC bullets

## Context
Also drives OCD people nuts.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch, modified

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
The recipe is actually intentional as it supports crafting with a potion to make the bullets with effects. This is intended and one of the side effects of the recipe system from Vanilla/Forge.

As shown here: 
![image](https://user-images.githubusercontent.com/1885466/40380599-79043424-5df1-11e8-8774-02a29137da08.png)
