### ISSUE TITLE
Inscriber issue

### ISSUE THREAD

**Issue by mukzon** [DarkPacks/SevTech-Ages#2716]
Modpack: Sevtech Ages Server 3.07

Inscriber slot didn't work as expected.
for example.

Inscriber Logic Press won't go to the top slot. If you force it by dragging the logic and put on the top slot it just drops the logic press on the ground. And if you tried shift clicking, it goes to the middle slot.

Printed Engineering Circuit won't go to the top slot. and goes to middle slot only (same problem like inscriber logic press)

Minecraft Version: 1.12.2

AE2 Version: rv5-stable-11

Forge Version: 14.23.3.2679

**Comment by artdude543** [comment]
Does not seem to be an issue. Are you sure you're doing this right?

![qneemjyu](https://user-images.githubusercontent.com/1885466/40866112-ee9d7bfa-65f3-11e8-948d-aae318ab96a4.gif)

**Comment by Aceship** [comment]
played on the same server, this happened
![mc-inscriber error](https://user-images.githubusercontent.com/5337323/40868663-2786c346-6639-11e8-85eb-4a08ce0540a6.gif)

**Comment by artdude543** [comment]
Am I going to assume you're using an Upper on this? In which it's working as intended. As it's pulling from the slot to the side. The AE inscriber is side specific. So whichever side it's on it will pull from that. The same for any other mod which has item transfer. This was a thing since AE was made and it's completely intention.
