### ISSUE TITLE
IE Pipe + Inductive Logistics Overflow Trash Crash

### ISSUE THREAD

**Issue by JaiSachdeva** [DarkPacks/SevTech-Ages#2741]
## Bug Report

Using Immersive Logistics overflow trash with IE pipes caused crash and I cannot load the save file anymore.

## Expected Behaviour

I tried adding a Overflow Trash to void excess naphtha that goes into the immersive engineering multi-block tank. I placed it right under the lower I/O port of the tank. The lever on the tank was in "on" state. It instantly crashed the game and I cannot load the save file now. 
 ## Possible Solution

## Steps to Reproduce (for bugs)

1. Create a Immersive Engineering multi-block tank.
2. Use the lower I/O port to both input and output certain liquid.
3. Place Immersive Logistics Overflow trash by breaking the fluid pipe adjacent to the port on the input side. Keep the lever on, just in case.

## Logs

* Client/Server Log: https://pastebin.com/wQuhtEUp
* Crash Log: https://pastebin.com/s9GXHcPy

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.161 (64 Bit)
* Launcher Used: Twitch
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment]
@malte0811 has this crash been reported to you guys before? And/Or want me to log it over on your tracker?

**Comment by malte0811** [comment]
There have been a few instances of this lately, but this is not our fault. @CD4017BE's overflow trash returns `true` in `hasCapability` for the fluid handler capability ([here](https://github.com/CD4017BE/InductiveLogistics/blob/054f5929e8e46383e8d1e45cc532015d5a3ba9f4/src/java/cd4017be/indlog/tileentity/OverflowTrash.java#L33-L34)), but only returns a non-null value in `getCapability` when the neighbour tile has a fluid handler ([here](https://github.com/CD4017BE/InductiveLogistics/blob/054f5929e8e46383e8d1e45cc532015d5a3ba9f4/src/java/cd4017be/indlog/tileentity/OverflowTrash.java#L46)). This behavior is against the contract for `get/hasCapability`, so the crash is their fault, not ours.
BTW, it's Inductive Logistics, not Immersive Logistics.

**Comment by artdude543** [comment]
Okay, thanks for the info!

**Comment by CD4017BE** [comment]
@malte0811 you misread the code a bit: The neighbour capability is not returned, it's assigned to a field.
What `getCapability` actually returns for the fluid handler capability is always the non-null value `this` ([here](https://github.com/CD4017BE/InductiveLogistics/blob/054f5929e8e46383e8d1e45cc532015d5a3ba9f4/src/java/cd4017be/indlog/tileentity/OverflowTrash.java#L48)).
The only exception where `null` is returned would be when the method gets called recursively because the block was connected to another Overflow Trash block, which is not the case here according to the issue description and then `hasCapability` would have also returned `false`.

So the the capability API contract is in fact not violated.

I could however let it return some dummy "do nothing" capability instance for recursive access just in case there is a multi-threading problem with the `RECURSION` variable.

**Comment by malte0811** [comment]
You're right, I misread the code. I tested this myself now and the behavior makes a lot of sense: It only happened while filling the tank through the overflow trash (neat concept btw). That happens in the server thread, the crash happens in the client thread, so I'd say this is a race condition. A possible fix might be replacing `RECURSION` with a `ThreadLocal` (never used them, but the name and the first few lines of the javadoc sound like they might be useful here).

**Comment by CD4017BE** [comment]
I decided to just handle `getCapability` differently for client side access since the block's behavior doesn't actually depend on the neighbor capabilities in a way that would be relevant for the client. So I can just skip all the recursion and neighbor checks there.
