### ISSUE TITLE
Cyclic Experience Collector Voids XP instead of storing it

### ISSUE THREAD

**Issue by Bhaaltazar23** [DarkPacks/SevTech-Ages#2898]
## Bug Report
When storing XP from player it just voids XP levels instead of storing it - tank remains empty

## Expected Behaviour
Experience was supposed to be stored in pylon

## Steps to Reproduce (for bugs)

1. Crafting pylon and placing it
2.Store XP from player to pylon

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171
* Launcher Used: Twitch
* Memory Allocated: 6 GB RAM
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Sevtech 3.0.8

**Comment by PrinceOfAmber** [comment]
Do you have any fluid cables connected to it?

Can you take a GIF of the bug happening maybe?  http://www.screentogif.com/  It works for me when I try it .

Player level bar is at the bottom . so the tank contents are not visible because the quantity is so large but its in there

![exp pylon](https://user-images.githubusercontent.com/621529/41500354-918f7916-7144-11e8-8df5-869c566a5688.gif)

**Comment by Bhaaltazar23** [comment]
![xp_pylon](https://user-images.githubusercontent.com/40314366/41500715-7fb9a916-7197-11e8-8139-2b048f01cc6b.gif)

Pylon is standing alone - I even placed it in the middle of the floor so it's not touching anything except the limestone.

**Comment by Bhaaltazar23** [comment]
I reinstalled the pack and problem went away - pylon is working now the way it is suppose to.

**Comment by PrinceOfAmber** [comment]
You can leave this closed if you want since im fixing it anyway, but a heads up turns out this bug ONLY happens if pylon is 100% empty . In this case the all button can delete exp from player without filling pylon. .   Link to 860 above
