### ISSUE TITLE
Baykok Items not available for second player when one completes it (party)

### ISSUE THREAD

**Issue by Sapler** [DarkPacks/SevTech-Ages#2928]
Hello!

Me and a friend of mine tried to kill Baykok to gain the bow for an easier time when it comes to ranged combat. We did the ritual together and he was deafeted. As we are in a party we both gained the Advancement. However only my friend was able to read and use the bow and arrows provided.. We tried to let me start the summoning ritual and me getting the final blow, still nothing.

Ive see the bug threads about this issue being present in 3.0.1 and suppose to be fixed in 3.0.2.. This is 3.0.8 and I have no idea what to do at this point. 

Attaching screens below.

https://gyazo.com/c2f14ceed468ada31dc8646bbe58ef7e

https://gyazo.com/d3d864d5bd9e8e586acb6c02c3f17808

**Comment by artdude543** [comment]
Sadly this issue is something which I don't think can be fixed when it comes to teams. We never able to reproduce this bug when we test ourselves as it also ways happens fine on _dedicated servers_. However, we know for a fact that LAN is buggy/does not work and most of the time cheeses itself to a point of being useless.

So if your using LAN sadly this is something we can't/won't be able to fix. Unless another mod shows up for syncing stages in teams.

The issue in question was indeed fixed in 3.0.2. I know that for a fact!

**Comment by Sapler** [comment]
This is on a online server hosted by Creeperhost, not a game shared with the LAN function. Is there a way to force the progression? I mean I do have the advancment "ticked off" I just cannot access the items.

**Comment by artdude543** [comment]
Have you re-joined the sever to check it's not a desync? Also try running the `/tf forcesync` command to make sure things are synced up.

Regardless of the issue tho. It's a rare case. Another get around would be to run this command on your person to get given the stage. `/gamestage add @p baykok`

**Comment by Sapler** [comment]
Rejoining did not work as ive tried that, but the /tf forcesync command did wonders! Thank you. I did not attmpt the /gamestage command as the previous one worked out.

Thanks alot Artdude543
