### ISSUE TITLE
BetterFPS Freeze on Load

### ISSUE THREAD

**Issue by antimodes221** [DarkPacks/SevTech-Ages#2970]
## Bug Report

Server fails to load.  Stops on BetterFps Update Checker]
[BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $

## Expected Behaviour
 Load freezes at BetterFPS Update Checker/WARN

## Steps to Reproduce (for bugs)

1. Run ./ServerStart.sh
2. 

## Logs

* Client/Server Log:
https://pastebin.com/7DjSPFHu
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)

* Launcher Used: None - server install
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: -
* Shaders Enabled: - 

## World Information

* Modpack Version world created in: None, world fails to create, freezes on load

* Additional Content Installed:

## Server Information
* Java Version: openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)

* Operating System: Ubuntu16.04
* Hoster/Hosting Solution: T3stN3t (owner of company)
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
The error has nothing to do with freezing or anything.

**Comment by antimodes221** [comment]
The load halts at that point.  Not sure what I should classify this as then

**Comment by Centros** [comment]
yeah im having the same problem what am i supposed to do at this point it wont progress past even after close it complacently and try to restart the server

**Comment by whitsyinferno** [comment]
yeah same problem anyone found a solution yet?

**Comment by Ccidaho** [comment]
I found a solution to this problem, for me it was giving an error saying that it failed to bind to port and by changing the port inside of the "server.properties" file from default (25565) to 25566 the server was able to run properly and work. 

I believe this error is due to the fact that this is my second Minecraft Server and that it was unable to choose that port to use as a result of having another server that already used it, even though the server wasn't on at the time.
