### ISSUE TITLE
Gold ore spawns outside of spawn range

### ISSUE THREAD

**Issue by GrimWrath** [DarkPacks/SevTech-Ages#2974]
## Bug Report

![2018-06-22_14-27-55](https://user-images.githubusercontent.com/4154791/41793073-fe9e37a2-7628-11e8-9264-de32da7ec192.png)
Gold ore is set to spawn between Y=5 and Y=30, according to Geolysis manual. Some of the ore has spawned out of bounds, at Y=41.

## Expected Behaviour

Gold ore should not spawn at Y=41.

## Steps to Reproduce (for bugs)

1. Find gold ore sample
2. Dig down

## Client Information

* Modpack Version: 3.08
* Launcher Used: Twitch
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled:No

**Comment by Stifling-Bossness** [comment]
There's a pull request to solve the erroneous entry #2880

**Comment by GrimWrath** [comment]
Will the fixed Y values be stated in the Geolysis manual as well?

**Comment by Stifling-Bossness** [comment]
I don't know about the manual, since I don't know where if it pulls the info from somewhere like the config (presumably not since it's inaccurate) or if it has to be explicitly written down. However, I'd say that more people get the ranges from the advancements menu than the manual, so it will be a fix for the _majority_ of players.

**Comment by artdude543** [comment]
Closing as we have the PR
