### ISSUE TITLE
Game crashes when clicking on Age 2 advancement tab

### ISSUE THREAD

**Issue by yesidiealot** [DarkPacks/SevTech-Ages#3017]
## Bug Report
I loaded into my world today and tried to click on the Age 2 advancement tab and the game immediately crashed. This has never happened before. I have optifine installed, but I installed it as soon as I got the modpack. I tried loading the save from a backup from before this started occurring, but the backup displayed the exact same behavior.

## Expected Behaviour
Should just open to the Age 2 advancements.

## Possible Solution
Seems to be some kind of rendering error for the progression tree visuals. 

## Steps to Reproduce (for bugs)
no idea, just started happening now.

## Logs

* Client/Server Log:
* Crash Log:
https://pastebin.com/GmUyq8hX
## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.171
* Launcher Used: twitch jar launcher
* Memory Allocated: 6 gig
* Server/LAN/Single Player: Single Player, but do open to LAN to play with my brother. This happened when it was in single player before opening to LAN. 
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 

* Additional Content Installed:

**Comment by artdude543** [comment]
Known: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63 and your on a newer version of Forge that is shipped with the pack which is causing the issue.

The pack is shipped with `2707` for a reason. But as this is a modified pack the issue is not caused by us. That and the issue is known which the Chisel guys.
