### ISSUE TITLE
Limit maximum age on a server

### ISSUE THREAD

**Issue by JoshHawley** [DarkPacks/SevTech-Ages#3054]
I would like to run the server in a particular age until some point where everyone on the server agrees to move on to the next age. It will probably be on a schedule of some kind. The goal of this is to explore the current age and build age appropriate towns/etc without feeling the need to "keep up" or race to the end of the pack.

So far I have figured out that the advancements are controlled in the config/triumph/script directory, and that in some of the files there is a setRewardFunction("triumph:stage-1_trigger") line that is probably what I am looking for. 

If I find all the lines that trigger the next stage and comment them out, will that work, or will I just be causing myself headache down the road?

**Comment by artdude543** [comment]
Your welcome to change the configs _(and yes you're looking at the right type)_ but in changing anything you'll lose support as you'll be using a modified pack.

But we won't offer/ship a system out of the box for it probs for the lifetime of the pack due to the number of changes needed and that we'd need a mod for it all. But you can comment them out sure. But then when you move on you'd need to trigger function for all players to move them on.

Which can be a pain and has been known to bug out. Hope this helps!

**Comment by JoshHawley** [comment]
Thanks for getting back to me. I will give it a try and report back.

**Comment by JoshHawley** [comment]
I found it was much easier to simply move the .txt file for the age completion advancement out of its directory. Then when ready to finish the age, move it back in and the restart server. Tested with age 0, worked great. I even made the melter/heater before hand and the age did not advance until I put the file back, restarted the server, then broke the heater/melter to get credit.
