### ISSUE TITLE
RFTools Filter Module in a Builder ( Quarry )

### ISSUE THREAD

**Issue by Voidfulqt** [DarkPacks/SevTech-Ages#3064]
## Bug Report
 I placed Desh Ore, Cheese Ore in the filter module. The filter module is set to whitelist with no extra options checked. The Builder will mine everything in the quarry area.Then I tried playing with the extra options with Oredict On, NBT , Damage match and Mod match. The Builder will run but it will mine nothing.

## Expected Behaviour
 The Builder should mine only the whitelisted blocks in the filter module.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8 Update 171
* Launcher Used: Twitch Launcher with Jar launcher
* Memory Allocated: 10240 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

**Comment by artdude543** [comment]
This won't work for a while due to issues with staging and fake players alike.

This should be resolved in the GameStages 2.0 we have planned but it does not have an ETA and we're midway through refactoring all the scripts for that update. So it will take time. Sadly you'll have to do things manually for a bit. Sorry.
