### ISSUE TITLE
SevTech Ages 3.0.8 crash on age 2 item render

### ISSUE THREAD

**Issue by Sbarb1** [DarkPacks/SevTech-Ages#3082]
## Bug Report

It flat out crashes

## Expected Behaviour

It flat out crashes

## Steps to Reproduce (for bugs)

1. Open the progression screen
2. Choose age 2 after completion of constellation paper

https://youtu.be/HyD2in2ISPY

## Logs

* Client/Server Log:
* Crash Log:
https://gist.github.com/Sbarb1/c11378ef1aaf10a8245a1debefa23673

## Client Information

* Modpack Version: 3.0.8
* Java Version: jre1.8.0_144
* Launcher Used: twitch
* Memory Allocated: 6,026
* Server/LAN/Single Player: Single Player
* Optifine Installed: Not unless it is in by default 
* Shaders Enabled: only default settings

## World Information

* Modpack Version world created in: 
  3.0.8

* Additional Content Installed: 
  None

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by monodemono** [comment]
This issue is completely different from the other one that you claimed was fixed by switching to ATLauncher.

Switching to ATLauncher does not fix all crashes, in fact switching launchers alone is not likely to specifically fix any crash. In your case, switching to ATLauncher probably switched to the JAR Launcher instead of the Native Launcher, or maybe selected a different version of java that is installed on your system.

Please stop commenting on everybody's threads that switching to ATLauncher fixed their problem for you unless you can provide hard proof as to specifically what the actual issue is and why that is a proper solution. You may have good intentions, but you're doing more harm than good.

**Comment by GoodBob** [comment]
https://github.com/DarkPacks/SevTech-Ages/issues/3170 
https://github.com/DarkPacks/SevTech-Ages/issues/3186
Is stated that it is a duplicate issue of 
https://github.com/DarkPacks/SevTech-Ages/issues/3118

Using this metric, this issue also qualifies as a duplicate of 3118. But since it wasn't marked as such, I thought I'd post a **possible** solution here as well.

Did I ever say that switching to ATLauncher fixed every crash?
I simply said this fixed the problem (admittedly surprisingly) for me. 

There is literally no harm in trying another launcher.

**Comment by monodemono** [comment]
The harm is in spreading inaccurate information. Unless you can tell me what it is specifically about switching to ATLauncher, what it is that the Twitch Launcher is doing wrong that's causing these crashes, your "fix" is not a fix, and can only cause further problems from people trying trying to "hammer in a screw" so to speak.

I appreciate that you're trying to help, but I'm simply asking you to stop unless you can provide ACTUAL HELP with an issue, not talking about what happened to work for you, by a stroke of luck, because you don't know what actual change occurred and don't know what you're doing.

Thank you for trying to help people, but I'm just politely asking you to stop because you don't have all the information and as such aren't actually helping.

As this has gotten drastically off topic at this point, I am now locking this issue, as this is an issue report, not a message board. If you wish to discuss this further, feel free to join our discord.
