### ISSUE TITLE
Never played before. Crashes on first time startup

### ISSUE THREAD

**Issue by Ar4bAce** [DarkPacks/SevTech-Ages#3091]
## Bug Report

Trying to start up for the very first time from Twitch but it keeps crashing.
## Expected Behaviour

Game should launch :)
## Steps to Reproduce (for bugs)

1. Press Play from Twitch
2. Press Play from Minecraft launcher

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/Ar4bAce/8f540d3f1835a63205314d96b8b71362

## Client Information

* Modpack Version: 3.0.8
* Java Version: Java 8 Update 171
* Launcher Used: Minecraft Launcher 1.6.91
* Memory Allocated: 12,288 mb in twitch settings
* Server/LAN/Single Player: Single Player
* Optifine Installed: Nothing added on other than modpack
* Shaders Enabled: Nothing added on other than modpack

I haver never made one of these before so I hope I followed the guidelines correctly

**Comment by artdude543** [comment]
This is a Vanilla bug since like 1.1 it's never going to be fixed on their side due to limitations and what not. But what most people do to get things working again is re-installing graphics drivers and rebooting the PC. Sometimes a re-install of Java helps.

But apart from that. There is nothing we can do since it's a Vanilla issue/bug. Sorry.
