### ISSUE TITLE
Unable to craft Grass Fiber Mesh

### ISSUE THREAD

**Issue by Myst031** [DarkPacks/SevTech-Ages#3102]
## Bug Report
Trying to craft Grass Fiber Mesh, however when ingredients are added in correct order not able to craft it.

## Expected Behaviour
Putting required ingredients to make grass fiber mess and it doesn't show the item.
![screenshot](https://user-images.githubusercontent.com/41174108/42667287-60e74ac6-85ff-11e8-88e5-fe98172284c7.png)

## Steps to Reproduce (for bugs)

1.  Uninstalled mod and reinstalled.

## Logs
[atlauncher log.txt](https://github.com/DarkPacks/SevTech-Ages/files/2190835/atlauncher.log.txt)

## Client Information

* Modpack Version: 3.0.8
* Java Version: (build 1.8.0_171-b11)
* Launcher Used: ATLauncher

## World Information
SevTech Ages 3.0.8

**Comment by artdude543** [comment]
Things are changed in 3.1.0 which _may_ resolve your rare case. But this issue is not reproducible at all sadly. I've tried in fresh instances on both Twitch/ATL and recipes are working fine. (Also tested on servers to double check)

Try again in 3.1.0 otherwise, this is an isolated issue. After release, if you're still getting the issue post a new issue with more data/logs (Including the crafttweaker.log to help on the matter)
