### ISSUE TITLE
Inventory Items Disappearing/Reverting to previous state

### ISSUE THREAD

**Issue by TKDWarrior** [DarkPacks/SevTech-Ages#3124]
## Bug Report

Items in my inventory are disappearing or reverting to a previous state when I save and quit and then relog on.  This is also happening to my friend that is playing on my world.  every time that he logs on he has two wagon wheels in his inventory and if he puts them in a chest and then plays for a while, no matter what he has in his inventory or collects, when he quits if he logs back on later he has the inventory with two wagon wheels and other stuff.  This bug is duping the wagon wheels and deleting whatever he has in inventory.  I wasn't having the same problem at first but now it's happening to me too. 

## Steps to Reproduce (for bugs)

1. Log off/quit
2. relaunch game and start world.  It happens every time

## Logs

* Client/Server Log: https://gist.github.com/TKDWarrior/5fe6255674406934343def6021003fea
* Crash Log: no crashes have occurred

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 update 171
* Launcher Used: Twitch
* Memory Allocated: 6Gb
* Server/LAN/Single Player: Single player, open to LAN - happens either way
* Optifine Installed: don't think so 
* Shaders Enabled: not sure how to figure this out

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: none

**Comment by xIceFox** [comment]
I have the same problem, evertime i log in i get my inventory at a previous state

**Comment by Walkman100** [comment]
@TKDWarrior @xIceFox did either of you change your Minecraft username before this started happening? it's happening to my brother too, and we suspect it's because he recently changed his username, as it's also happening on a different world on 1.11.2 created before he changed his username.

**Comment by xIceFox** [comment]
Yeah, I changed my username recently.
I know that it is a problem with UUID and a problem with playing online/offline.
Save your inventory in a chest before logout :)

**Comment by Walkman100** [comment]
Ok cool, thanks for the confirmation.
Now to figure out how to fix it...

**Comment by artdude543** [comment]
So in regards to _patching_ UUID changes it won't be easy at all. _(And some mods won't even support it)_ due to how mods store player data. For the Vanilla Game data, it should be as simple as re-naming the player data file to the new UUID and updating the OP.json/Whitelist.json _(if needed)_.

But for mods it's complicated and some store data all over the place. So losing your inventory is not only the main thing you'll lose from changing a name.

Tbbh: Names changing (and then updating references) is not really supported in Vanilla itself. As the game won't know about the changes, when you then bring modded into the picture it's a whole headache. It's not impossible. Just time consuming and a lot of effort for let's be fair; little gain.
