### ISSUE TITLE
ServerStart.bat does not have "pause" at the end

### ISSUE THREAD

**Issue by drhead** [DarkPacks/SevTech-Ages#3132]
## Bug Report

Sevtech's server start batch file doesn't have a pause command at the end, so if the server closes for some reason, the window disappears before I can see what went wrong.  Most server packs have a pause which makes it easier to quickly diagnose a crash without having to open up the log files and I don't see why this one shouldn't.

## Expected Behaviour

Upon server close (whether normal or by crash), a "Press any key to continue" prompt should display.

## Possible Solution

Add "pause" to the end of ServerStart.bat.

## Steps to Reproduce (for bugs)

1. Run server in a way that it'll fail real quick, like having eula=false or something
2. Behold, as the server window closes before you can see that you need to set eula=true

**Comment by artdude543** [comment]
This is an intentional thing as of current. The server scripts are due to a revamp soon. But we work on the hindsight that people running servers, know what they are doing. Thus the current scripts are designed around that.

But this won't happen for a few revisions. You're more than welcome to modify your own scripts to give you the option.

But thanks for the suggestion!
