### ISSUE TITLE
How do i make progression individual?

### ISSUE THREAD

**Issue by Sullivan2001** [DarkPacks/SevTech-Ages#3158]
I have recently bought a server for me and my friends to play on but the progression system is server wide. So if one of us complete a quest we all complete it. Is it possible to make the progression system individual instead of being linked server wide? I have access to all mod files and config if I need to change anything. Many thanks!

**Comment by artdude543** [comment]
Okay, so progression is not _server wide_ it's to a single person as it's using the Vanilla advancements system. The only thing which will sync to players is if you set up teams using the Together Forever mod which comes with the pack. That's the **only** mod which will allow syncing to all players in a team to ensure players are at the same point.

Otherwise, the entire pack is single player based, this is the intention of the pack. If you have something which is somehow giving all players the same advancements. This is on you as nothing is natively shipped with the pack which does that.

Unless your being mistaken about the global server announcement that Vanilla posts when someone completes one. This is still single player based and it's just a message nothing more.

But TLDR: We don't ship anything which does what you're stating. Only a single mod can do this but it needs to be configured beforehand. So that leads to your having something additional installed which is causing it. But that voids support as then your running a custom installation.

And as you did not follow the template at all. I'll let the bot finish the post.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by Sullivan2001** [comment]
Yeah, the server has the Together forever mod installed, it is pre-installed so not a lot I could do about it, I looked in the config files of the server and have set what I believe is causing this to happen to false instead of true, im going to test it and I will get back to you. Thanks for your help 👍
