### ISSUE TITLE
server files on curse broken and causing weird things to happen to advancements

### ISSUE THREAD

**Issue by Shadow6751a** [DarkPacks/SevTech-Ages#3163]
## Bug Report

**REMOVED DUE TO IP ADDRESSSES LISTED**
I logged in opened my advancements page found it was not working then disconnected after reconnecting I had the vanilla advancements on the exact same server without the server ever going down 

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.12.2-14.23.4.2707
* Launcher Used: twitch
* Memory Allocated: 12,228mb ram to my modpack
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
default server world and a singleplayer world that was working in singleplayer but did not work once I transferred it
* Modpack Version world created in:
3.0.8
* Additional Content Installed:
no

## Server Information
* Java Version: 1.12.2-14.23.4.2707
* Operating System: windows 10
* Hoster/Hosting Solution: running it of my own computer with a static ip computer has a 1080ti a i7-8700k 32 gb ram and about 1 terabyte of storage available so hardware is probably fine
* Sponge (Non-Vanilla Forge) Server: not sure downloaded of off curse from the link above

If someone is going to recommend I use a different website please include the link I have been trying to get this server working for almost 10 hours now about 4 were setting up a static ip and I am getting really tired of repeatedly trying new things and every single time it does not work
one of the times I logged into the server I got the vanilla advancements shown below
<img width="840" alt="3" src="https://user-images.githubusercontent.com/41488029/43105813-4068c0c4-8ea4-11e8-869c-9811a0f9d694.PNG">
but every other time it looks like this even on the exact same server all I did was disconnect then reconnect to the server and it gave me vanilla advancements edit it will give me the vanilla achivements but it will not show the normal advancements in sevtech ages it acts as though the game is vanilla even though the mods are in the server and were showing earlier and I even went through my server files and found the advancements section and it showed all of the stages/ages
<img width="839" alt="capture" src="https://user-images.githubusercontent.com/41488029/43105819-4edd04e4-8ea4-11e8-9877-db5f24f898ad.PNG">
I would highly appreciate any help at all

thanks, Shadow6751a

**Comment by Shadow6751a** [comment]
@artdude543 please help

**Comment by artdude543** [comment]
This is a complete a _you_ issue. We don't offer server support in this regards. I've tested the server files just now and it's all working fine. You're either missing something or breaking files somewhere along the line. Also tagging me won't get you any support as I have them globally disabled.

First, you ignored the rules of the template by posting your log on the issue. It **clearly states** to use PasteBin or Gist no exceptions to this.

But the download we offer is not broken. So don't come into here creating an issue that it is when it's not nor is there sufficient evidence to suggest otherwise. I don't mean to be an arse when it comes to replying. But servers should always be setup by people who know what they are doing.

We don't give any support based on issues like this when it's lack of knowledge. Also, you pasted an IP address of a player so congrats on that!

But reading your issue this is what I'm going to tell you.

- Your breaking the files somewhere along the line no question about it.
- You had it working once and then it _broke_ suggests to me that your server is currupt or does not have write access to update progressions on users. As that's done on world save.
- The message stating "nothing seems to be here" is what it says on the tin. Your missing the files. If it can't find them it will show that message. You need to debug your server setup and use the internet for additional support. Alternative would be to rent a server from a host such as Creeperhost.

Don't get offended by anything I said. But see from our view point when no effort is put into the issues and you ignore key parts and can't provide key information. Servers are there for people with knowldge on how to run them. This is why hosts and providers are a thing to take this hassle away from the players. So you can one click install and be done with it.

All the server files are vetted and tested before we upload them. So we know 100% for a fact they work out of the box. Nothing can contest otherwise on that matter.

But hopefully you can get this resolved. I've helped as much as I'm prepared on the matter as server debugging takes more time than clients and we don't have that time on hand to such manners.

**Comment by LethalDumpster** [comment]
Hey Shadow, I might have a solution. 
Be sure that your launching 'ServerStart.bat' (windows might call it a 'windows batch file').
When you do, a console will open and do some stuff super slowly for a long while. This applies to *seemingly* every modpack. They may not always say 'ServerStart.bat', it might just show the name of the modpack or something. But it *seems* to never be that 'minecraft_server' thingy.

Ive had what looks to be your exact issue for a few days now. Infact I found your first post here on the github when Artdude immediately closed it. Then I found this post and waited for someone to respond to you so I can get an answer aswell. But according to Artdude, learning to hosts servers isnt allowed... Thats some of the dumbest s*** ive ever heard. Hope this works out for you, I know it worked for me. -kinda. Im hosting on an old PC with 3gb of ram, so after the server is up for a minute it runs out and bluescreens XD

**Comment by artdude543** [comment]
So your soultion is not really a _soultion_. It's how the server system works (as the same for most major modpacks).

The `.bat` or `.sh` files for starting servers has always been a thing in modpack servers. FTB/ATLauncher etc.. ship the same kind of files. Using the `minecraft_server.jar` to start the server is wrong. All your doing then is loading the Vanilla Server. The `forge-universal-xxx.jar` is the one which boots Forge which then uses the `minecraft_server.jar` to load the **Forge Server** not the **Vanilla** one.

All big modpacks will take an age to load server and client. It's the norm.

_And yes, I'll gladly edit comments. This is a PG issue tracker redacting your language also counts as a removal._

Learning to host a server is fine. I never once said he could not. I advised that prior knowledge or even some kind of knowledge is ideal. Forge servers are not an easy thing to run/manage when you run into issues. We are **not** server support and will never be. You can call me out all you want, does not bother me a single bit. Just don't use fowl lanague including stared out.

And yes editing Shadows message was wrong of me when it included public IP address. I'll put them back right away!

**Comment by LethalDumpster** [comment]
Im aware of the ip situation. I know that bit was edited out by you. Its apreaciated. No you didnt say he could not learn, but your message added up to the implication. It really, really did. And thankyou for telling me about no use of star key curse words. Ill avoid foul language all togather.

**Comment by Shadow6751a** [comment]
@LethalDumpster thank you sooooo much for the help its nice to finally have someone at least attempt to help I don't care at all if it works because you actually tried to help me unlike artdude all he has done is tell me I'm doing things wrong and has offered no help (go ahead post my ip I really don't care) and has been really mean to me (I wanted to say words that would have a little more emphasis  but I did not feel like having to make a new account. I do realize I don't know a whole lot about this as this is my first time trying to do this and I am sorry I have made mistakes but all I wanted was a little help so thank you so much lethalDumpster for actually taking some time to help someone who has no idea what they are doing 


also @artdude543  you were wrong lethal dumpsters solution actually worked and your solution did not 
I can not thank you enough lethal dumpster you are so helpful and I am so glad you helped me
