### ISSUE TITLE
Millenaire, the mod that added villagers before Minecraft did

### ISSUE THREAD

**Issue by felinoel** [DarkPacks/SevTech-Ages#3164]
Why isn't Millenaire in this pack? It is an eight year old mod that is still going strong and even adding new content all the time! Not only that but it spawns its content on already generated chunks meaning that anyone updating their modpack will find the mod working like normal with nothing missing from the mod content or even if someone were to rise to a new Age where new cultures happen the new cultures will still spawn on already generated chunks. This would help those poor testificates out with their villages torn apart by adding new villagers who are able to be available only when the player is at the right Age.

Also it is highly customizable and not hard to customize, Millenaire by default has 11th Century cultures but one could very easily create cultures for higher tech levels and even make those cultures use modded elements in their structures. Furthermore the Millenaire "dev team" are very helpful and many on it would enjoy helping craft new higher tech cultures for this.

## Mod Details
* Name: Millenaire
* CurseForge Link: https://minecraft.curseforge.com/projects/millenaire

**Comment by monodemono** [comment]
Not likely to be added. I for one don't think it fits the scope of this pack.

**Comment by artdude543** [comment]
So this mod was talked about from the start. But it did not meet the needs we were after. That and for the design of the pack would require a lot of custom changes. (Pretty much disabling large portions of the mod) which we did not feel warranted the mod in the end. (That and the time needed for someone to work on it was not valid)

Structure generation as you've seen in the pack. Pretty much all mods had theirs turned off including some village changes. The pack is not meant to be easy or the world giving you items. Handling the staging side of that would also cause a nightmare.

You're not meant to see things before `X` stage. So with this mod, we'd have to stage more blocks/tiles in the on top of the current ones. At the current time staging blocks so they show as others. Is a factor in rendering lag due to how it works. We don't need to add any more bottlenecks to the game.

I understand your point but the mod is not for the pack. Some parts I'd love but having to disable 60% of the mod feels wrong against the mod. And it's a waste of loading time in the end goal when the mod is useless.

I'm sure we could work with the team to make it easier for us. But from the technical perspective, it's not something do-able like locking generation behind stages. As it won't work on servers. Most things are complicated on the basis it **has** to be server friendly. Which staging is a complicated factor? Like the block, hiding is only possible as that's client side. But other things are not that easy.

Hope this answers your question enough. But I'm happy to answer others if you have them.
