### ISSUE TITLE
The Twilight Forest Uncrafting Table doesn't do anything.

### ISSUE THREAD

**Issue by swestrup** [DarkPacks/SevTech-Ages#3176]
## Bug Report

The Twilight Forest Uncrafting table has an altered recipe, so I presume it was intended as a craftable (and usable) item in the game. I'm in Age 3 of V3.08 and just made a crafting table. It appears unable to uncraft chests, iron bars, armor, or actually anything at all. 

## Expected Behaviour

While I would not be surprised if some items were non-uncraftable, I would have expected to find *something* it could work on.

## Possible Solution

I'm guessing that something in the huge number of changes to the standard recipes has broken the functionality of the table. Alternatively, you may have disabled so many things from being uncraftable that it's now neigh-impossible to find something that can be uncrafted.

I would be perfectly happy if the uncrafting table could only uncraft twilight forest items, or even if the uncrafting table were removed, and the stoked crucible would be able to melt down twilight forest armor and weapons.

## Steps to Reproduce (for bugs)

1. Craft an uncrafting table.
2. Try to use it.

## Client Information

* Modpack Version: 3.08
* Java Version: OpenJDK 1.8.0_171.b11
* Launcher Used: MultiMC5
* Memory Allocated: 4 GB
* Server/LAN/Single Player: Single Player.
* Optifine Installed: No.
* Shaders Enabled: None.

## World Information

* Modpack Version world created in: Early, maybe 3.0.1

**Comment by artdude543** [comment]
This is intended. Both from Twilight and Us. By default, they don't add support for mods and other recipes than Vanilla. This has been a thing since they added the block. Sometimes it will work and others not. But we can't add _any/more_ support as this is on their side. And they're not planning on fixing it either. So it's pretty much a useless block. But most users use if for Vanilla recipes. So it will stay in the pack.

Hope this helps! 😄
