### ISSUE TITLE
my home

### ISSUE THREAD

**Issue by TheElementKingYT** [DarkPacks/SevTech-Ages#3205]
so i went exploring and i never wrote the cords for my base and i lost this is in the stone age so i dont have a map so i would appreciate if when we went into creative mode we would be able to use the map without the book

**Comment by monodemono** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by artdude543** [comment]
This won't ever be done. Due to how staging works. Changing to Creative would then require all stages to be given to a player. Meaning network syncing and world updates. Which with the number of stages we have the pack is not ideal and you'll end up timing out from the world. Which then changing back to survival you'll need to have the stages you should not have removed. Which means again more syncing/updates leading to timeouts.

I can see the point in this. But at the end of the day, it's RNG. You should leave breadcrumbs to your base. Or do what the natives did back in the era of using landmarks to work out how to get from A to B.

Hope this helps!

_Also please use the template next time. We have one for a reason_

**Comment by TheElementKingYT** [comment]
oh ok but i figured out something else i can create a new world with the same seed since my base is right neer spawn
