### ISSUE TITLE
Cyclic's Block Placer, placing a stripped log, makes the server/game crash and unbootable.

### ISSUE THREAD

**Issue by Ncrpts** [DarkPacks/SevTech-Ages#3223]
## Bug Report

When the block placer from Cyclic attempt to place a stripped log from Primal core, it result in a server crash on servers or full game crash in singleplayer. forcing to use mcedit to fix. making it impossible to reload that world again until manually fixed.

## Expected Behaviour
Not crashing the game.

## Possible Solution
When this happens only solution is to open the world.dat in mcedit, remove the placer, and restart on the edited world.
To prevent this from happening, i suggest blacklisting stripped logs from the game or placer, or wait for a fix from cyclic mod.

## Steps to Reproduce (for bugs)

1. Place "Block Placer" by Cyclic
2. Right click placer to open it's GUI.
3. Insert "stripped oak log" or any other stripped log from Primal core in the placer
4. turn the placer on from gui or using redstone.
5. Crash.

## Logs

* Client/Server Log:
* Crash Log: 
[crash-2018-08-04_08.34.26-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2259449/crash-2018-08-04_08.34.26-server.txt)
[crash-2018-08-04_12.51.27-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2259450/crash-2018-08-04_12.51.27-server.txt)

## Client Information

* Modpack Version: Latest (3.0.8)
* Java Version: irrelevant (multiple)
* Launcher Used: irrelevant (old and new twitch)
* Memory Allocated: 10gb+
* Server/LAN/Single Player: Server AND Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed: no

## Server Information
* Java Version: uknown
* Operating System: linux
* Hoster/Hosting Solution: VG
* Sponge (Non-Vanilla Forge) Server: no

**Comment by PrinceOfAmber** [comment]
This is the same issue as with FarmingForBlockheads blocks  

https://github.com/PrinceOfAmber/Cyclic/issues/865

Best solution is for fix to happen on both ends:
- Cyclic should use a "FakePlayer" instead of passing null player to block placement (also some try-catch safety checks so instead of crashing it just spams the log
- The other mods (Farming for blockheads / Primal Core) should check if the given player is null , since there could be any number of modded blocks that are using this for placement without a player instance.

**Comment by artdude543** [comment]
The Cyclic crash (for the OP) has been resolved in a mod update. And will in the 3.1.0 update.

The other mods are aware of the issue and we will update them mods as soon as releases are made 🙂
