### ISSUE TITLE
Frame freze

### ISSUE THREAD

**Issue by GhostFire90** [DarkPacks/SevTech-Ages#3251]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

LOG:https://www.dropbox.com/s/vwhoc19kjdq04cu/latest.log?dl=0 (Pastebin wouldn't let me)
Bug: Lag even though I have the latest java 64x and the correct arguments I get dropped from 100fps to 5 every 6-7 seconds.
Expected: to not do that.
Suggestion: No clue why this is happening so I can't really suggest anything
Steps: Literally do anything Video: https://www.dropbox.com/s/odtcb7rjjnlcgk1/2018-08-11%2022-15-05.mp4?dl=0
Settings: java:jre-8u181-windows-x64 modpack version: 3.0.8 launcher: twitch mem:(recommended) -Xmx3072m -Xms256m -XX:PermSize=256m 
singleplayer
no optifine
no shaders
word was created in 3.0.8
no additional content

**Comment by artdude543** [comment]
_Removed file link due to private information is contained_

_Bot Response_

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
