### ISSUE TITLE
Crashes about wrong recipe at Age 2 

### ISSUE THREAD

**Issue by 3094300238** [DarkPacks/SevTech-Ages#3304]
## Bug Report

Actually there is a serious problem about the wrong recipes.In right situation,when I bring a bronze ingot to a stone anvil,just put a hammer and knock it several times it will become a bronze plate.But in my server, just becomes a bronze stick.

## Expected Behaviour

I just had a Sev Tech: Ages 3.0.8 server pack downloaded and installed by Curseforge. And also when playing a singleplayer mode there is no bug about recipe instead of Multiplayer.

## Possible Solution

I have no idea. All attempt has failed.
Seeing the latest.log and you will find that some script documents haven't been initialized properly.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2303172/latest.log)

## Client Information

* Modpack Version:3.0.8
* Java Version:8.0
* Launcher Used:HMCL
* Memory Allocated:3200MB
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

## World Information

* Modpack Version world created in:3.0.8 without installing any other mod

* Additional Content Installed:No

## Server Information
* Java Version:8.0
* Operating System:Windows 2016 Server Version
* Hoster/Hosting Solution:Aliyun
* Sponge (Non-Vanilla Forge) Server:No ,just a forge server pack you give.

Some grammar I made may be a mistake because I am not a native speaker, so sorry for my poor English :-(

**Comment by artdude543** [comment]
If you getting the wrong outputs from recipes you have missing/broken scripts which are needed. Re-Upload all the files to the server (obviously keep the world folder) and then try again. You also need to make sure your using the server files we supply https://minecraft.curseforge.com/projects/sevtech-ages/files/2570735 as this is created/updated by us.

Once you've done all that you'll be fine. Also you won't crash from a recipe (apart from a Chisel related one which is fixed in the next update) but even if you did crash you failed to attach a crash report. Also the template states "Do Not Upload Logs to Git" So use PasteBin or Gist. Otherwise the issue will be auto closed.
