### ISSUE TITLE
Rock crystal doesn't exist/can't find

### ISSUE THREAD

**Issue by sizzurp34** [DarkPacks/SevTech-Ages#3308]
## Bug Report

I find rock crystal samples on the surface. Using a tough dowsing rod I try to find rock crystal ore in the area and nothing comes up. I dig holes in the surrounding area to see if the rock crystal is located deeper than the tough dowsing rod can't detect and nothing appears. I even went into creative mode to see if rock crystal ore existed and I couldn't find any.
## Expected Behaviour

Rock crystals existing.
## Steps to Reproduce (for bugs)

1.Find a rock crystal sample
2.Try to find rock crystal ore beneath the surface using a tough dowsing rod in the surrounding area.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_181-b13
* Launcher Used: Twitch
* Memory Allocated: 6.5GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: No

**Comment by artdude543** [comment]
Rock Crystals are found in the world. This is bad RNG tbh. The Ores generate near bedrock (sometimes eaten by other generation) they can spawn in an adjacent chunk, however (like some other ores) but 100% they do spawn as Ore Generation was heavily tested before release.

We can't control the generation flow of the game. Which is the number one cause for Ores being generated on top of again from Lava/Structures/Other Mods etc... as that's just how the Ore Generation Layer works.

But the Ores are there you need to dig/explore some more. And you _will_ find chunks with nothing in them due to generation.
