### ISSUE TITLE
Server Crash during Initialization

### ISSUE THREAD

**Issue by DuckyQuack** [DarkPacks/SevTech-Ages#3325]
I've never posted an issue on GitHub before... bare with me

Here is the Crash report 
https://pastebin.com/Bnce5wDs

Here is the Server Log
https://pastebin.com/rn8KNUHc

I've tried reinstalling the server
I've tried reinstalling Java
I've tried _turning it off and on again_
I don't know what else to say...

**Comment by artdude543** [comment]
This error is caused by having a server running in a cloud storage folder such as OneDrive. As your on Windows 10 by default your documents folder is the "OneDrive" one. So please move the server out of that either onto your Desktop or Downloads folder.

This would be the same case for Dropbox/Drive etc...

But that's your issue here. As the syncing/dynamic changes to the file system cause the process to lose access to files upon times.

**Comment by DuckyQuack** [comment]
Thank you!
