### ISSUE TITLE
bronze pickaxe recipe is wrong

### ISSUE THREAD

**Issue by tyler-robotnik** [DarkPacks/SevTech-Ages#3363]
![2018-09-13_18 47 07](https://user-images.githubusercontent.com/23531428/45520170-10ca6380-b786-11e8-8ee3-34b99724e98a.png)
![2018-09-13_18 43 33](https://user-images.githubusercontent.com/23531428/45520171-10ca6380-b786-11e8-9f8a-6a1670cf059e.png)

the recipe for the bronze pickaxe uses copper plates instead of bronze plates.
there is also no recipe for the copper pickaxe.

**Comment by monodemono** [comment]
1) This has been reported a thousand times, please use the search feature next time.

2) As stated in all those other reports, this is fixed in the next release.

3) Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by tyler-robotnik** [comment]
firstly i would like to say that i did search for this issue, but i was unable to find any other posts regarding this. i am new to github and so i may have easily misunderstood how searching for things works. i simply searched "bronze" under issues, and it gave no results. i took this as meaning there were no issues involving the word "bronze" and so i proceeded to make this post. if i could be instructed on how to properly search, that would be highly beneficial. 

secondly, regarding the issue template. i do not understand what i have done wrong. i read the template and then created a post that encompasses all relevant information.

#1: describe current behavior. i explained that a bronze pick was made with copper plates
#2: describe expected behavior. by extension of explaining current behavior, i explained the expected behavior.
#3: steps to reproduce. i included pictures as steps for reproduction. 
#4: logs, system information, and modpack information. as this is not a crash report, logs and system information seemed irrelevant and so were not included. i did however neglect to mention that i am playing in 3.0.8, which i should have.

was i supposed to use the template as a form and fill out all of the information in it, rather than simply using it as a guide as to what information i am supposed to include?

i apologize for my ignorance, and any inconvenience i have given you with what is apparently something that has already been reported numerous times.

**Comment by monodemono** [comment]
Well they're out there, so you didn't search very hard. As for the template, yes, you are supposed to fill it out like a form.

And lastly, do NOT email me a copy of a message you've sent in an issue report, I don't need a duplicate. I am now locking this issue report as it's dreadfully off topic, and if you email me again I will blacklist you too.
