### ISSUE TITLE
Purpurite in wrong Stage

### ISSUE THREAD

**Issue by Kaelthalon** [DarkPacks/SevTech-Ages#3370]
## Bug Report
Purpurite Stone is listed as Stage 4

## Expected Behaviour
Like the rest of PrimalCore, it should be Stage 0

## Possible Solution
Make it available in Stage 0, I like the purple color 💜 

## Logs
None available (Staging issue)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 9.0.1
* Launcher Used: Twitch
* Memory Allocated: 5GB
* Server/LAN/Single Player: All of the above
* Optifine Installed: No
* Shaders Enabled: ?

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: N/A

**Comment by Kaelthalon** [comment]
I think I put this as the wrong thing... this is supposed to have been a feature request, right?

**Comment by monodemono** [comment]
Well this is kind of a grey area between bug and feature. On the one hand it's a bug because it's wrong, but on the other hand it's a feature request because it might be the way it is on purpose. You did fill out all the important information though, that's what's important.

That being said... It is actually the way it is on purpose. Purpurite is made from purpur, which is found in the end cities in the end, which you can't reach until age 4, that's why they're staged to age 4. So sorry, but this is something that won't change.

Thank you for following procedure though.
