### ISSUE TITLE
Issue #2663 Solution

### ISSUE THREAD

**Issue by badookey** [DarkPacks/SevTech-Ages#3397]
Hi, I know this is the incorrect place to put this but I have the solution to Issue #2663, and since it is the first result on Google I wanted to help anyone else who comes across the issue. The reason why the .bat file instantly disappears is you are using 32bit Java and the script is requesting to use 4Gs (32bit Java cannot have more than 1G). Therefore either install 64bit Java or modify the settings so that -Xmx1G replaces -Xmx4G.

**Comment by monodemono** [comment]
The reason it happens varies from person to person, it's not always a problem with the target architecture of the version of java you have installed.

So this is not only the incorrect place, but it's also mildly incorrect information.

Please leave support to the proper support channels (e.g. the discord) so that users in need can get accurate assistance.
