### ISSUE TITLE
RS converts Buckets into Empty Bladders

### ISSUE THREAD

**Issue by Phantum** [DarkPacks/SevTech-Ages#3399]
## Bug Report
If I use the autocrafting from Refined Storage with Fluids, even though my recipe is set to use the full bladder, it'll fill the bucket with water, then craft the recipe, and give me an empty bladder. 

Converted 88 buckets to bladders this way :/

## Expected Behaviour
Refined storage should fill the bladder, use it in the craft, and then return the empty bladder afterwards, not use a bucket.

## Possible Solution
Not sure, might be a recipe issue?

## Steps to Reproduce (for bugs)
https://puu.sh/BBE3e/6084787694.png
https://puu.sh/BBE4g/d171990007.png
https://puu.sh/BBE55/a0b24c4fd8.png

If you need a video of it, I'll do it tomorrow, Killer migraine tonight.

## Client Information
* Modpack Version: 3.0.8
* Java Version: latest
* Launcher Used: Jar Launcher
* Memory Allocated: 12,288 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled:

## World Information
* Modpack Version world created in: 3.0.3/2/1 something like
* Additional Content Installed:

## Server Information
* Java Version: Latest
* Operating System: Linux
* Hoster/Hosting Solution: Nodecraft

**Comment by artdude543** [comment]
Would need reporting to RS. This issue is not in our control. But due to the refactor on RS side you won't get any help from them. Would be best to hold off till 3.1.0 is out with the new RS. Unless you want to make a mini pack with RS and Primal to test the bladder with another recipe to then report to RS with the refactored version.

Not a whole lot we can do with the old RS version, but you go the latter please update us here. But we'll monitor this issue internally, and update if we notice anything.,

Thanks for the report!

_Side note: Please don't use the wording "latest" it means nothing to us as latest can mean anything. Use precise version numbers as it can make a massive difference :)_

**Comment by Phantum** [comment]
10-4 that's what I had my Java set to in twitch launcher and just did it out of thoughtlessness, I'll try to track down the java versions on any future reports.

I'm guessing once RS is updated and bring back the crafting options it will fix a lot of the problems that have been seen as of late
