### ISSUE TITLE
Fix for Astral/Age 2 crash:

### ISSUE THREAD

**Issue by Bucket777** [DarkPacks/SevTech-Ages#3463]
Since the mods where too eager to lock the previous threads, I am posting a new one. 

There are a few issues that is caused by using a newer version of forge. After I downgraded to version 14.23.4.2707 (as recommended by the sevtech manifest.json) these issues where resolved.

Astral starmetal ore rendering crash
Stews not getting consumed
Waterwheel item rendered incorrectly/duplication when breaking.

**Comment by monodemono** [comment]
I specifically told you not to file duplicate issues of things that are already fixed. If you would search for these issues, you'll see they are indeed fixed in the next version of the pack, you just have to wait for its release.

If you continue to disregard our warnings, and file duplicate issues regardless of the fact that they're already fixed, you will be blocked from being able to post issues at all.

If there's a new issue, that hasn't been reported, and that isn't already fixed, please, don't just feel free to post it, feel strongly encouraged to post it, so we can actually fix it. This current issue report you've filed is not helpful in any way, shape, or form. Especially considering you didn't follow the directions on how to post a proper issue report.
