### ISSUE TITLE
Nature Compass: Mod doesn't support extended Biome IDs [3.1.0]

### ISSUE THREAD

**Issue by Lothrazar** [DarkPacks/SevTech-Ages#3612]
## Bug Report
In the very beginning stage zero, im using Natures compass to find abyssal biomes. When i open it it says "doesn't support extended Biome IDs" as in title

## Expected Behaviour
I expect all biomes have name and full information

## Possible Solution
Some mod that adds biomes has an issue?  Or natures compass

## Steps to Reproduce (for bugs)
Go to age zero

get natures compass and use it

![biome ids](https://user-images.githubusercontent.com/621529/54255381-1de9c480-4515-11e9-9c23-42816d1300b2.PNG)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by justinrusso** [comment]
In this case there is no issue, just that the Natures Compass' mod does not let me blacklist the JEID biome.

If someone would like to PR a change thats backwards compatible to how it currently works - maybe by converting the old to the new config, that would be great. Ideally the blacklist should use resource locations rather than the biome name like it does currently.
