### ISSUE TITLE
[3.1.1] Mekanism cardboard box craftable but unusable in stage 2

### ISSUE THREAD

**Issue by Seramme** [DarkPacks/SevTech-Ages#3636]
Cardboard box is craftable in age 2. However when I put a regular chest in it (by right-clicking the chest with the box in hand and then breaking it) the resulting item is set to stage 5. This makes any boxed chests unusable until stage 5. The only way to recover them earlier is by switching to creative.

Either the cardboard box itself should be set to only be available in stage 5 or the "boxed item" version of it should work in stage 2.

**Comment by sk2048** [comment]
I think this is related to #3628 

Mekanism crafting results have an empty NBT tag, we're currently staging items `<mekanism:some_item>.withTag({mekData: {}})` which matches the item in JEI. Crafting recipes have result `<mekanism:some_item>.withTag({})` - this also needs staging.

Lots of Mekanism items are craftable early because of this, in addition to those already mentioned I have found:

- Scuba Tank
- Jetpack
- Seismic Reader
- Walkie Talkie
- Robit
- Network Reader
- Energy Cubes
- Bins

There's probably more.

**Comment by ZeekDaGeek** [comment]
If you would like to know other blocks that have this issue I can confirm that the Quantum Entangloporter also cannot be placed after crafting.

**Comment by ZeekDaGeek** [comment]
Even trying to apply those suggested changes to my server and client it still constantly rejects the items and throws them on the floor.

```
		<mekanism:machineblock3:0>.withTag({}),
		<mekanism:machineblock3:0>.withTag({mekData: {}}),
```

**Comment by sk2048** [comment]
That's the intended behaviour, what the proposed script changes are intended to do is stop you being able to craft Mekanism items early.

**Comment by ZeekDaGeek** [comment]
Maybe I have a different issue then, I'm in the creative age and I can't even hold it in my hand.

**Comment by sk2048** [comment]
That is a different issue, yes. It appears to be correctly staged to five and whilst it's recipe is unstaged its crafting ingredients are all unobtainable until stage five.
