### ISSUE TITLE
[Twilight forest] Trophy pedestal ineligible

### ISSUE THREAD

**Issue by nilujebu2** [DarkPacks/SevTech-Ages#3719]
Hello,
I'm sorry for my english, i'm french.
I have a strange problem in twilight forest. When i put a trophy on pedestal trophy to enter in maze, i have a error "twilightforest.trophy_pedestal.ineligible".
I think is a bug but i'm blocked with that, i can 't have journeymap if i can't enter in maze
![2019-04-12_22 00 48](https://user-images.githubusercontent.com/49571501/56063879-d010e800-5d70-11e9-84bb-d85f4138e313.png)
 ^^
Hope you can fix it.

Thank you very much

**Comment by Dutchs** [comment]
The only bug here is that the message is missing proper localization and its not showing you a readable message, which i believe was fixed in 3.1.1(at least for english localization, i dont think TF has french localization)

double check the advancements for the TF and that you have all the required boss kills for entering.
