### ISSUE TITLE
Crash on new download startup

### ISSUE THREAD

**Issue by rjzvara** [DarkPacks/SevTech-Ages#3789]
## Bug Report

trying to launch from jar launcher and goes though mod prep but crashes immediately after no ingame main menu 

## Expected Behaviour

immediate crash with no main menu

## Possible Solution

i don't know it is a completely clean download for 3.0.8

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/7mgGdCjW

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.51
* Launcher Used: twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: none

**Comment by sk2048** [comment]
This might be related to another bug where you can't assign certain keys and extra mouse buttons to options in Minecraft 1.12.2 due to a bug in LWJGL - deleting your options.txt file might solve this. However I'm not sure, you should try the Discord to see if anyone there has seen this before.

You could try updating the version of Java you're using, 1.8.0_51 is ~4 years old at this point...
