### ISSUE TITLE
Crash when launching game

### ISSUE THREAD

**Issue by DasekaPC** [DarkPacks/SevTech-Ages#3800]
## Bug Report
I was looking for a modpack, so I chose this one. I downloaded it, start and it crashed. The first time it said that CTM had an error, so I updated it. But it keep crashing no matter what.

## Steps to Reproduce (for bugs)
1. Launch the game
2. Game crashed when loading

## Logs
* Crash Log: [https://pastebin.com/5z8j1stx](url)

## Client Information
* Modpack Version: 3.1.1
* Java Version: 8 Update 11
* Launcher Used: Twitch
* Memory Allocated: 5 GB
* Server/LAN/Single Player: ---
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by Streamcyper** [comment]
I would suggest heading over to the [discord](https://discord.gg/darkosto) as this is not a bug, but support request.

**Comment by sk2048** [comment]
You have not installed SevTech 3.1.1, the mod versions in your crash are mostly consistent with 3.0.8 other than your changes. Your current crash is caused by you updating Forge. I am guessing your original crash was caused by using the wrong version of Optifine for an old version of the pack.

I suggest starting over.
