### ISSUE TITLE
Creeping moss not changing biome in Hunting Dimension

### ISSUE THREAD

**Issue by talktome2** [DarkPacks/SevTech-Ages#3811]
3.1.1

After crafting and setting creeping moss to Darkland, enter Hunting Dimension and right click.  I get the message that the biome as changed, but the biome in the chunk does not change.  Tried leaving and re-entering Hunting Dimension, restarting world, entered Creative and tested different creeping moss's and it never changes.

**Comment by sk2048** [comment]
Unfortunately this happened as a consequence of adding JEID, without that mod the pack could not be updated past 3.0.8 because simply updating mods took us over the item ID limit.

This has been fixed through the addition of JEIDsI in 3.1.2, which is planned for release shortly. You cannot add this mod yourself due to other changes that were made to make this support easier.
