### ISSUE TITLE
Quantum Entangloporter suddenly deactivated

### ISSUE THREAD

**Issue by BlackFranky** [DarkPacks/SevTech-Ages#3832]
## Bug Report
The Quantum Entangloporter is displayed as unknown item belonging to stage creative_unused.

## Expected Behaviour
Until yesterday it was available to be build and placed.

## Client Information

* Modpack Version: SevTech: Ages 3.1.1 
* Launcher Used: Twitch
* Memory Allocated: 8GiB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in:  3.0.8 (updated 3 weeks ago)

## Server Information
* Hoster/Hosting Solution: Nitrado
* Sponge (Non-Vanilla Forge) Server: No

**Comment by Stifling-Bossness** [comment]
I believe this is part of a larger issue which affect all Mekanism machines. Occasionally, pressing the keys for more info on Mekanism machines either in JEI or in your inventory makes them "unknown" (at least I believe this to be the case). This issue is typically solved by a server restart, so you can try that as a temporary solution.

**Comment by sk2048** [comment]
Probably resolved already so closing, please report again if the issue still occurs in 3.1.2 when it comes out.

**Comment by BlackFranky** [comment]
Why do these items get put into the wrong stage instead of getting no stage at all?

**Comment by BlackFranky** [comment]
I have the same issues with the Resistive Heater and Fuelwood Heater. Those are not changed in the master branch.
