### ISSUE TITLE
Players get max resistance buff

### ISSUE THREAD

**Issue by fujishiro-m** [DarkPacks/SevTech-Ages#3874]
## Bug Report
1. Get resistance from Nutrition.
2. Enter the Hunting Dimension.
3. Player get Max Resistance buff, no longer take damege.

Maybe,There 2 causes
1. Hunting Dimension gives Player Max Resistance,4 seconds .
2. Nutrition extends the resistance buff.

## Expected Behaviour
Hunting Dimension gives Player Max Resistance,4 seconds .
Nutrition do not extends the resistance buff.

## Possible Solution
Perfect no damage is not fun.
But I dont have good Solution.
For temporary fix, I edited Nutrition config no longer give resistance.

## Client Information

* Modpack Version:3.1.2 Hotfix1

## World Information

* Modpack Version world created in:3.1.2a

**Comment by sk2048** [comment]
Thank you for this information, it had been reported players were becoming invulnerable, but I wasn’t getting anywhere with trying to track down why.

**Comment by mingear** [comment]
OMG YES. I have been invincible!! Thank you. I drank milk and that seems to quickly remove the resistance buff for a split second and resets it from being the max resistance buff. DRINK MILK BOIZ

**Comment by Zarvera** [comment]
So it's Hunting Dimension?
God i've been trying to figure out what's wrong for days but didn't even knew what to report.
My last attempt to get rid of immortality involved respeccing AS perks to not include health bonuses as i thought it bugs out with Nutrition bonus, but i haven't visited HD yet so idk. This one's really esoteric, thank God someone figured it out

**Comment by fujishiro-m** [comment]
I did some test.
I tried with only the following mods.
    forge-14.23.5.2838
    Nutrition 4.3 and 4.4
    Hunting Dimension 1.0.39
However, the problem did not reproduce.
Perhaps there are other causes as well.

**Comment by Zarvera** [comment]
I did a quick check and it's 100%, absolutely, undeniably triggered by entering Hunting Dimension.
Haven't had this problem for days since i did not need anything there and as soon as i just dived in i became immortal again.

**Comment by sk2048** [comment]
@Zarvera hunting dimension seems to be one trigger, but others have reported having the issue at other times. Nutrition definitely seems to be a common thread, did you have resistance as a result of your nutrition being good enough?

**Comment by Zarvera** [comment]
Absolutely yes, i keep it at 100%. 

I think i've managed to reproduce it in a test instance, adding whatever i suspected one by one and checking the dimension. I had two biggest: Construct Armory and Astral Sorcery with it's "Perk" or whatever that always boggled my mind - so called "Dodge Chance" (Vicio branch). What the hell is a dodge chance in Minecraft? This isn't Final Fantasy 2
Anyway, Nutrition with HD by themself don't trigger immortality as fujishiro-m reports, CA is not at fault either, but after adding AS and attuning myself to Vicio and allocating a few points into the stars that add "Dodge Chance" trait and entering HD i immediately became immortal.
I removed AS and baubles and entered the dimension again, after a few hits not doing damage (probably due to new minecraft nutrition regen + retarded strong CA armors) i started receiving damage again as it should be. Then i added baubles and AS back and entered HD again and, again, became immortal.

**Comment by sk2048** [comment]
So the issue is likely down to AS and Nutrition not playing nicely. Interesting, thank you. I will see if I can recreate this and then go hunting for a solution.

**Comment by sk2048** [comment]
I recreated it while attuned to Aevitas so maybe the bug only requires you to be attuned.

**Comment by Zarvera** [comment]
Good job narrowing it down, sk2048. Both probably conflict over something in plater.dat or something
But do you mean you didn't even need to enter HD? Because that seems to be the trigger

**Comment by sk2048** [comment]
Hunting Dimension gives the player Resistance 255 while they're standing in the portal. I just did it through commands. (`/effect @p minecraft:resistance 10 255`).

**Comment by sk2048** [comment]
This is purely an issue with Astral Sorcery and changes made by them to how combining potion effects works.

It can be recreated without nutrition present at all.

Thank you to everyone here who has helped narrow down the causes of this issue, it would have taken me a long time to find it on my own.

**Comment by fujishiro-m** [comment]
Thank you everyone.
I understood that it was an AS problem.

**Comment by lemings68** [comment]
Me and a friend just started Astral Sorcery (currently making the second tier crafting table) so no infusions yet. I've had it happen back in Age 1 without any AS, and now my friend is getting it in Age 2. I'm not sure AS is the trigger here.

**Comment by sk2048** [comment]
AS makes modifications to the way potion effects combine. This happens whether or not you progress through AS. It is 100% the root cause, which I have demonstrated conclusively in my issue report on their page.

Progressing through AS is not the trigger, but if AS' modification to potion combination were to behave similarly to vanilla this would not be an issue.

**Comment by RadGH** [comment]
This also applies to the health buff from Nourishment i think. I was at 89 life which is way more than I expected for Age 2 (but that was with full nourishment AND health perks from AS). I also had the resistance bug and was invulnerable. After a /kill and some eating I am back down to 57 max health.

I disabled the resistance effect in the nourishment config but the extra health will probably still be a problem. Is there any known workarounds, maybe involving a command block and a timer? Particularly for a multiplayer server.

**Comment by Kungaren** [comment]
Would there be a way to remove the extra resistance buff that comes from the hunting dim? would solve the problem until it's properly fixed maybe?

**Comment by armogedden101** [comment]
So after a bit of experimenting, I found that along with entering or exiting the hunting dimension, it is also triggered by Knightmetal weapons/tools. The stalwart effect triggers and upgrades your nutrition resistance to resistance 3. Is that a way to disable the stalwart effect so this does not happen but players can still use the material as it is one of the best materials at stage 3? Playing SevTech Ages 3.1.2-hotfix .1.
