### ISSUE TITLE
Replacement for rocks/ stone as the "filler" for ores.

### ISSUE THREAD

**Issue by xAtea** [DarkPacks/SevTech-Ages#3888]
Context

While I love the pack, a friend of mine did bring up something slightly annoying that I had to agree with. Namely, how ore generation is done.

Hiding ores as standard stone, while effective for balancing, also leaves a slight bitter taste of wasted resources and simply the lack of "I found this, but don't know what it is" feel the pack seems to be going with. For ore to 'magically' appear once you hit an age and be nonexistent in any form prior means that there's little point to 'explore' as such due to stones on the ground being hidden ore deposits, mining may be destroying resources, etc.

Solution/idea: New blocks /ore deposits for the pack specifically, for use with progression. Making an 'unidentified ore' (including a color for the various ores) for each oretype, nearly unusable in its current state but can later be converted via a recipe/ combination with another item into their proper ores. Some could have minor uses pre-age, like very rough tools or weapons ('harder' Orestone tools due to the presence of ore perhaps?)

Just a thought to make mining early game still 'useful' without it possibly losing ores or causing problems. And overall just would have a nicer feel.

**Comment by sk2048** [comment]
I'm not really sure this solves anything. If we add a bunch of new ore variants - let's say before you reach the right age all ore is `Poor Metal Ore` or `Unknown Crystal` and you can mine it and make tools out of it early, but they're inherently bad tools. As suggested, they have different colours based on what they will become.

A new player will stumble on these and think they're useful and mine them up. How are they to know that the poor metal ore outside their base was a huge iron mine waiting to happen? Suddenly they've wasted resources in a way that doesn't happen when it's just stone.

And it also goes quite a way to spoiling the idea that unidentified ores are a mystery. If you've read up on the pack and you know that a poor metal ore with a reddish tinge is actually iron, and you mark it in advance of reaching the age it defeats the idea that every time you reach a new age you need to go exploring and find new ores.

Building on this, I don't really understand how you're ending up removing all the ore before reaching the right age at present. The veins are huge! And you're not really expected to be digging large underground tunnel systems to find ores due to the surface sample system.

In addition, you can distinguish between hidden surface samples and plain old boring rocks. Right clicking a rock will:
1. Drop a rock item if it's just a rock
2. Do nothing if it's a surface sample in disguise.

It might be worth the time to add an unidentified surface sample so inexperienced players stop removing the surface samples before they reach the right age.

Maybe I'm missing something here, but I don't believe implementing this would actually help new players.

**Comment by xAtea** [comment]
The idea sk2048 is the ability to 'convert' the orestone to the proper ore later, avoiding the 'well I dug a cave and didn't know I just destroyed a diamond deposit' problem. And yes, it would  'remove' the complete unknown... however, let's be realistic.

If you yourself were a miner, or adventurer, or what have you, and you found a cave of crystals. Or an unusual stone formation/ oretype you had no way of identifying, would YOU not mark it on a map to come back to later? Or would you simply shrug, forget about it, and leave the potential lost.

The whole idea of this is to give experienced players a bit more of an easy time due to foresight, and beginning players a chance to learn more 'evenly'. Instead of "world's regenned, now  I apparently have to hunt iron down somehow"

Speaking of, adding an actual block would do the job handily. Starting Age 1, unlock a recipe for an 'ore identifier'... Basically a machine to take the unidentified ores, wash/ clen them into usable ore clumps that are currently in-game. Then perhaps it be an upgrade system, where you  craft the next tier to continue identifying ores. In this way it would cut out a part of the world having to hard-regenerate too, as the ores wouldn't have to change at all. You'd still be able to mine ores you couldn't identify (assuming you own the correct tier pick) but they'd be almost useless to you without the ability to identify them.

I kind of like the idea of players not automatically 'knowing' that the reddish ore is redstone or iron... instead only able to tell it by the color of the veins in the rock until it's processed into a usable ore. Would incentivize having someone as a miner more than ever, bringing bulk ores to a blacksmithy to be identified and used.

And yes, I know this probably adds more steps than necessary but.... come on. This is Sevtech, the mod which requires at least 3 steps to make leather. So washing the ore and identifying it prior to it beign a usable form is hardly far-fetched of an idea.
