### ISSUE TITLE
crash on start up help plz 

### ISSUE THREAD

**Issue by dustin7789** [DarkPacks/SevTech-Ages#3892]
## Bug Report
i crash up on start up on stage 2 of forge

## Expected Behavior
crashes when expected start up

## Possible Solution
idk?

## Steps to Reproduce (for bugs)
nothing i just start up

## Logs
Crash Log: https://pastebin.com/TzTxfzz3

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.12.2 forge-14.23.4.2707
* Launcher Used: twitch 
* Memory Allocated: ram? if yes 2gb 
* Server/LAN/Single Player: NA
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment]
Your log is either incomplete or otherwise the process is being terminated by an issue in the java virtual machine.

Please check to see if there is a folder called `crash-reports` or else a file with a name that begins `hs_err`. If either of these exist, please share the latest file.

Though it is probably worth mentioning that SevTech requires 4GB of RAM (we recommend 8GB) and I would expect it to crash due to running out of memory with only 2GB assigned.

**Comment by dustin7789** [comment]
thats the entire log like it just cuts off there 

> Your log is either incomplete or otherwise the process is being terminated by an issue in the java virtual machine.
> 
> Please check to see if there is a folder called `crash-reports` or else a file with a name that begins `hs_err`. If either of these exist, please share the latest file.
> 
> Though it is probably worth mentioning that SevTech requires 4GB of RAM (we recommend 8GB) and I would expect it to crash due to running out of memory with only 2GB assigned.

Thats the entire log dude so idk

**Comment by sk2048** [comment]
Again, 2GB of RAM is not enough to play SevTech.
