### ISSUE TITLE
Can't connect after server update

### ISSUE THREAD

**Issue by jvanollef** [DarkPacks/SevTech-Ages#3972]
## Bug Report
My players and I have been away from the server for a while, so I just updated the server from version 3.0.8 to 3.1.2 Hotfix (like I said it's been a while). 

After I updated the server, which I'm pretty sure I did correctly, any time I try to connect, I get this error:
internal exception: io.netty.handler.codec.decoderexception: java.lang.indexoutofboundsexception: readerindex(8) + length(1) exceeds writerindex(8): PooledUnsafeDirectBytBuf(ridx: 8, widx: 8, cap: 8)

## Logs
There doesn't seem to be any sort of crash log for this incident on either end, client or server.

## Client Information

* Modpack Version: 3.1.2 hotfix 1
* Java Version: 1.12.2
* Launcher Used: Twitch Launcher
* Memory Allocated: 8GB
* Server/LAN/Single Player: Singleplayer/Multiplayer
*  Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information

* Modpack Version world created in: 3.0.8

**Comment by sam-kirby** [comment]
You say you experience this issue in both single player and multiplayer but only talk about a server environment, could you please clarify this?

You have removed the section for providing server details, why? Please complete that section.

I'm also going to need logs to identify what's going on, ideally from both the server and the client.

**Comment by jvanollef** [comment]
Whoops, yea this was my mistake for sure.

It's just multiplayer.

* Java Version: 1.8.0_201-b09
* Operating System: Windows 10
* Hoster/Hosting Solution: To be totally honest, I'm not sure what this means
* Sponge (Non-Vanilla Forge) Server: Not sure for this either.

Logs: https://pastebin.com/EfF7PkDR

Crash Report: https://pastebin.com/UN4ZHB77

**Comment by sam-kirby** [comment]
Looking at your server log, it seems you're starting a vanilla Minecraft server. It can't load a lot of things and will have corrupted your world so hopefully you have a backup.

Your client is unable to connect as JEID alters the packet format so that large IDs can be sent. This results in the vanilla server sending information your modded client can't interpret.

**Comment by jvanollef** [comment]
How could that be possible? I downloaded the new server files straight from the 3.1.2 hotfix curseforge download. Why would it be trying to start a vanilla server?

**Comment by sam-kirby** [comment]
Due to licensing restrictions Forge cannot include vanilla Minecraft code, instead during installation Forge downloads a vanilla server typically named `minecraft_server.1.12.2.jar` so that it can load it and apply modifications to it at runtime. It can only do this if you start the server by invoking `forge-1.12.2-14.23.5.2838-universal.jar`, as would happen if using our scripts.

**Comment by jvanollef** [comment]
So you're saying I must have updated the server incorrectly. I have a copy of the world and prestige files, so it's not a huge deal. I'll just have to try and update again, and do it correctly this time.

Thanks.

**Comment by sam-kirby** [comment]
Pretty much. Use the discord link above if you run into more trouble.
