### ISSUE TITLE
Twitch modpack crashing

### ISSUE THREAD

**Issue by darealGameknight14** [DarkPacks/SevTech-Ages#4014]
### Bug Report
I just downloaded your modpack from Twitch, but unfortunately it crashes.
### Expected Behavior
The launcher should download the requested items, then proceed to the forge modloader (Minecraft loading screen)
### Steps to reproduce
1. Browse modpacks on twitch, find this modpack, click install, and wait.
2. Once it is finished, click play under "My Modpacks".
3. In the Minecraft launcher, click play on the "Ages" installation.
4. Error and crash log.
### Logs
https://pastebin.com/R79d47hP
### Client Information
Modpack version: 3.1.2 Hotfix 1
Java Version: Java 8 Update 231
Launcher used: Default twitch launcher for Minecraft
Memory allocated: 6G in xmx and 2G in xms
Server/LAN/Single Player: Singleplayer
Optifine installed: No
Shaders enabled: No

**Comment by sam-kirby** [comment]
Unfortunately this is not a bug caused by us, it’s one introduced by Mojang in the new native launcher. You can read more about it here: https://bugs.mojang.com/plugins/servlet/mobile#issue/MCL-12570

You have two solutions: the simplest is to use the jar launcher which you can switch to in Twitch’s settings under Minecraft. Alternatively you can download the file manually (link in your log) and place it in the expected location.

**Comment by sam-kirby** [comment]
The link is on line 5 of your log and the expected path is on line 7.
