### ISSUE TITLE
I just progressed to stage 1 and it shows the new achievements but has not given me the new recipes to start the next set of achievements. I also do not have cheats on and do not have acces to the commands that they say to use to fix the problem for others with similar issues What do I do? Expected behavior: give me the recipes and allow me to be stage 1  Possible solution: Unsure  Steps to reproduce: 1).play to stage 1  2).thats all i did 

### ISSUE THREAD

**Issue by isaiah323** [DarkPacks/SevTech-Ages#4066]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by isaiah323** [comment]
this is 100% not a support request this bug will not let me continue the mudpack please help me

**Comment by isaiah323** [comment]
Please don't make me have to re submit my bug

**Comment by sam-kirby** [comment]
I do not consider this a bug report on which I can act; I cannot reproduce it based on the steps outlined in your issue title(?), you have included no log and no information about your environment, and I have no way to determine whether this is an issue with your setup or one of the many interacting mods in the pack.

This could be caused by anything, from a file failing to download to your machine to an as yet undiscovered bug in vanilla Minecraft that causes advancement rewards not to trigger in rare circumstances. But based solely on 87 words that must sum up hours of play time and thousands of actions how am I supposed to figure it out? If you are serious about me considering this a bug report then know that it would have been closed for failing to complete the issue template. The information we ask for is genuinely useful.

In addition, were we to find a bug based on your report, you still wouldn't necessarily get what you want here - personal support in recovering your world so you can continue. Support is handled on the Discord. Here, we would fix the source of your problem for the next pack release, if possible, making sure that it no longer occurs in the first place.

At worst, this is an intermittent bug that can easily be worked around using commands. Even though you have cheats disabled. You can enable cheats temporarily at any time by turning them on when using the Open to LAN feature, or permanently by modifying the data stored in `level.dat` using an NBT editor. If you need help figuring this out then please ask about it on the Discord.
