### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by RealZezzo** [DarkPacks/SevTech-Ages#4096]
My SevTech: Ages crash every single time on boot.

Minecraft were allocated 10GB. 

PC Specs:
CPU: i7-7700k | GPU: GTX 1080 | RAM: 16GB

Log (I don't get a crash log):
https://puu.sh/FC8i3/bd2bdf96a9.log

greetings

**Comment by sam-kirby** [comment]
There is nothing in your log that suggests an issue.

Please check for a file called `hs_err_pid<number>.log` in the modpack folder. If one is present it likely means the operating system is stopping Java usually due to bad drivers or outdated Java.

This file will contain your access token, so if you don't know how to interpret it make sure to remove that prior to uploading.

**Comment by RealZezzo** [comment]
It crashes without an error.

Have no `hs_err_pid<number>.log` in my folder :(
