### ISSUE TITLE
Minecraft Failed To Start [Optifine]

### ISSUE THREAD

**Issue by dannyjim-ml** [DarkPacks/SevTech-Ages#4150]
Seems to be a new issue with 3.13. Using Optifine 1.12.2 Version D3 causes the game to fail to start - installing newer versions of optifine works fine but doesn't improve performance.
Client Log
https://pastebin.com/RvnrVTw0
### Bug/Issue
Installing Optifine 1.12.2 Version D3 causes Minecraft to fail to start.
### Steps to Reproduce
1) Drag and drop Optifine Version D3 for 1.12.2 into Mods folder
2) Launch
### Client Information
Modpack Version: 3.1.3
Java Version: 1.8.0_251-b08 x64
Launcher Used: MultiMC
Memory Allocated: 8GB
Server/LAN/Single Player: Server
Optifine Installed: Yes, Optifine_1.12.2 HD_U_D3
Shaders Enabled: No
### World Information
Modpack Version world created in: 3.1.2 Hotfix 1

**Comment by sam-kirby** [comment]
Optifine E2 and earlier are incompatible with Forge build number 2781 and later. sp614x/optifine#2061

The current recommended Forge build for 1.12.2 is 2854, which is used in SevTech 3.1.3. It is worth noting that this crash occurs all the way back on SevTech 3.1.0, which used build 2815 of Forge. This is not a new issue in 3.1.3.

For example, here is the same crash occurring in an instance with just Forge 2838 (used in 3.1.2) and Optifine D3:
https://pastebin.com/94JwbwLT

We cannot downgrade Forge to "fix" Optifine, particularly when Optifine already has releases that are compatible with this build of Forge. The pack updates since then include mod updates that have fixed various major issues and depend on newer versions of Forge than 2780, not to mention the many improvements in Forge itself in the year and a half since 2780 was released.

If you believe there are regressions in Optifine's functionality then you should file an issue with the Optifine developers. However, before doing that I suggest you join the Discord and see if there are any configuration options in Optifine you may have overlooked that will give you the performance boost you are looking for. https://discord.gg/darkosto
