### ISSUE TITLE
horse attached to cart makes player disconnect

### ISSUE THREAD

**Issue by Greenvilleguy** [DarkPacks/SevTech-Ages#4192]
## Steps to Reproduce (for bugs)

1. get on horse
2. use button to attach horse to transportation cart
3. get kicked

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:latest
* Java Version:latest
* Launcher Used:twitch
* Memory Allocated:more than enough
* Server/LAN/Single Player:LAN
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
We do not directly support Open to LAN multiplayer. It is poorly implemented in Vanilla and is a very shaky foundation for modders to build on. Many mod authors will not support it either.

You can contact the mod author directly to see if they are willing to fix this issue - if so we will happily release an update including the fix in the future.

Otherwise, I suggest you use a dedicated server. You can run a dedicated server on the same machine as you have a client running on, provided you have sufficient RAM, without performance penalty.
