### ISSUE TITLE
Sevtech Server Crashes Upon Joining

### ISSUE THREAD

**Issue by IHAZACOOKIE** [DarkPacks/SevTech-Ages#4197]
## Bug Description
Ever since I created an automated farm (from Industrial Foregoing) and an autonomous activator (from Cyclic) to water Mystical Agriculture crops my friends and I would crash the server every time we would load back in. My suspicion is probably the autonomous activator.
I would also like to note that we are at Age 5 where we need to gather 10k resources to create singularities to spawn the final boss and get creative items, the thing is that it requires us to gather 10k death compasses, which means we need 10k death compasses that are unique to one another and we have to store that in a storage medium (currently we are storing it in the ME system).

### Did this behavior use to work in the previous version?
Yes, the previous version in which this bug was not present was: 3.0.8

## Steps to Reproduce (for bugs)

1. Load Sevtech and the server
2. Join the server
3. Kicked from the server and be presented with a message saying "Server Closed"

## Logs

https://pastebin.com/ZZQifprD

## Client Information
* Modpack Version: 3.1.3 Beta
* Java Version: Latest
* Launcher Used: Minecraft Launcher
* Memory Allocated: 5GB
* Server/LAN/Single Player: Server
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in: 3.1.3 Beta
* Additional Content Installed: None

## Server Information
* Java Version: Latest
* Operating System: Windows 10 Home 64-bit
* Hoster/Hosting Solution: Hosted from home with server files provided
* Sponge (Non-Vanilla Forge) Server: 1.12.2

**Comment by sam-kirby** [comment]
The NBT data can be stripped from compasses through crafting, allowing it to stack.

Your server has crashed due to there being an item overflow somewhere, it cannot process all the entities in the world before the watchdog timer stops the server.

You should disable the watchdog timer, login and immediately run the command `/kill @e[type=realdrops:item_loot]`. This will take a while - over a minute.

You should then setup a system to handle the items.

For assistance with this please use the Discord.
