### ISSUE TITLE
Issues with Lan Multiplayer

### ISSUE THREAD

**Issue by yftechno** [DarkPacks/SevTech-Ages#4220]
Hello,

I was going to play this modpack with my wife today, and we figured out how to join as a group (we read to use /tf invite, but it was actually /togetherforever). But when she was went into the group she was able to finally see the advancements, but not partake in completing them. It seemed as it was only if I completed something would it take it as done, is there a way to fix that so she can partake in doing things as well?

**Comment by sam-kirby** [comment]
We do not directly support Open to LAN multiplayer. It is poorly implemented in Vanilla and is a very shaky foundation for modders to build on. Many mod authors will not support it either.

You can contact the mod author directly to see if they are willing to fix this issue - if so we will happily release an update including the fix in the future.

Otherwise, I suggest you use a dedicated server. You can run a dedicated server on the same machine as you have a client running on, provided you have sufficient RAM, without performance penalty.

For assisstance setting up a server, you can use the Discord at https://discord.gg/darkosto
