### ISSUE TITLE
SevTech: Ages Of The Sky

### ISSUE THREAD

**Issue by KatKazam** [DarkPacks/SevTech-Ages#4245]
So I downloaded the zip file and how do i play it now. Im used to just downloading mods on twitch. I know how to import mods but not the other stuff in the zip and why does the zip file only have a few mods in it?

**Comment by sam-kirby** [comment]
In the Twitch Launcher, click Create Custom Pack, then click the word "import". Select the zip file and wait for it to install.

The zip contains a manifest which Twitch uses to select the mods to download during import, which is why there are so few mods in the zip.

**Comment by sam-kirby** [comment]
Note that this is an early alpha, which is why we have not made it more readily available yet. You may experience world breaking bugs, and worlds you start now may not be compatible with the release version of the pack.

If you are not technically competent, you should probably wait until the pack is ready for release to the wider audience and is made available on the launchers.

**Comment by justhayleyk** [comment]
> 
> 
> In the Twitch Launcher, click Create Custom Pack, then click the word "import". Select the zip file and wait for it to install.
> 
> The zip contains a manifest which Twitch uses to select the mods to download during import, which is why there are so few mods in the zip.

On my Twitch it is Create Custom Profile (not pack) in case this is confusing to others.

**Comment by XiNaru** [comment]
@Sam Kirby
thanks now it works

**Comment by DK909GitHub** [comment]
what do i set generator settings to for server

**Comment by sam-kirby** [comment]
> what do i set generator settings to for server

`"Sky Block"`
