### ISSUE TITLE
World is invisible: Pictures included.

### ISSUE THREAD

**Issue by CranberryPunch** [DarkPacks/SevTech-Ages#4276]
## Bug Description
When loading Singleplayer, the world works fine, world loads- it's playable.
After creating a server for me and a friend to play on, however...
https://imgur.com/a/PVPAEP9

Should be noting that placing/destroying blocks SOMETIMES loads the chunk, but not all loaded chunks stay loaded.

### Did this behavior use to work in the previous version?
I wouldn't know, as I just downloaded this modpack on 9.19.2020

## Steps to Reproduce (for bugs)
1.) Download modpack server files
2.) Launch [Server.](url)

## Logs
SevTech Ages> Logs> latest.log= https://pastebin.pl/view/b09907d4
Then upload the latest/crash logs to PasteBin or Gist. DON'T Upload them to GitHub -->

## Client Information
https://imgur.com/a/On7ObqP
* Modpack Version: included in imgur post above
* Java Version: 1.12.2
* Launcher Used: Twitch
* Memory Allocated: 13G
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

## World Information
* Modpack Version world created in:same as the one under ##Client Information
* Additional Content Installed:None

## Server Information
* Java Version:1.12.2
* Operating System: Windows 10
* Hoster/Hosting Solution: Port Forwarding
* Sponge (Non-Vanilla Forge) Server: No Idea what that is

##Additional Information:
https://github.com/DarkPacks/SevTech-Ages/issues/4157
this post is a perfect representation of my issue.
Server latest.log= https://pastebin.pl/view/c2782536

**Comment by sam-kirby** [comment]
Could you please upload your server log?

**Comment by CranberryPunch** [comment]
where is that located?

**Comment by CranberryPunch** [comment]
nevermind found it- updated main post with https://pastebin.pl/view/c2782536
also found this thread, which is a good representation of my issue as well- https://github.com/DarkPacks/SevTech-Ages/issues/4157

**Comment by sam-kirby** [comment]
#4157 isn't much use as we never got any information from the poster.

But from the server log your issue is fairly obvious; you're running a vanilla server. As SevTech modifies the format of the information sent between server and client to allow for more blocks it cannot understand the vanilla protocol.

You must use a SevTech server for multiplayer. As you say you are downloading the modpack server files, your issue is likely as simple as you're launching the wrong thing. You must launch `forge-1.12.2-14.23.5.2854.jar` instead of `minecraft_server.1.12.2.jar` as the latter is just the vanilla game. It must be present for Forge to start.

This requires specific options be passed to increase the Java memory limits, which is why we provide a start script in the form of a batch file for Windows or shell script for Linux/macOS. If youu are having difficulty running `ServerStart.bat`, then either:
1. the version of Java installed is too modern; Forge for 1.12 requires that you use Java 8
2. you have a 32-bit version of Java installed and need to install a 64-bit version
3. By default, we select the server JVM. This is no longer installed by default on Windows. Edit `ServerStart.bat` and remove `-server` only on the line that begins `java -server -Xms%MIN_RAM%...` so that it reads `java -Xms%MIN_RAM%...`

If you need further help with this, I recommend asking on the Discord - there is a server support channel. You will generally get a faster response there. https://discord.gg/darkosto
