### ISSUE TITLE
SevTech Ages Crashing When Loading World

### ISSUE THREAD

**Issue by yasscraft03** [DarkPacks/SevTech-Ages#4332]
## Bug Description
I tried to create a new world and have fun but after starting the creation of the world and after i saw all the tips in the screen,  the game crashes

### Did this behavior use to work in the previous version?
Yes this problem worked in the previous versions

## Steps to Reproduce (for bugs)
1.Creating world
2.Crash
3.

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/zWfU8zmS

## Client Information
* Modpack Version:3.1.7
* Java Version:1.8.0_221 64-bit
* Launcher Used:Official Minecraft Launcher
* Memory Allocated:5GB
* Server/LAN/Single Player:SinglePlayer
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:
* Additional Content Installed:10/08/2020 ‏‎11:41:34

**Comment by sam-kirby** [comment]
You say that Optifine is not installed, however your crash report tells a different story: 
`Optifine Installed: True (OptiFine_1.12.2_HD_U_C6)`

Optifine is installed, and it is very old. It is likely causing your issue. Please remove it or update it to F6-pre (or F5 if you do not intend to use shaders).

If your issue persists, please attach a new crash report without Optifine.

**Comment by yasscraft03** [comment]
Im Sorry That i Typed that its off and thank you for the help i will try it out

**Comment by Braboskov** [comment]
Hi !
I have the same problem than you.
i think it's du to RAM (im not an expert but when i up my RAM used on MC, i load a world and it crash but iv tried before with 4G RAM and its worked!
after trying with 6G RAM, that crash! 
PS: sorry for my english im french im literally a shit in english.

**Comment by Shadow-Hunt3r** [comment]
I'm having this same issue when loading the game as well

OS: Linux Mint 21.1
Launcher: MultiMC 5
I have attempted this issue with varying amounts of RAM(4GB-8GB)

Expected Outcome:
Launches fine and loads a new world without any issue

Actual Outcome:
Launches fine but crashes when loading a new world

heres the [Log Dump](https://github.com/DarkPacks/SevTech-Ages/files/12213581/hs_err_pid28748.log) after it crashing after trying without editing the `ulimit -c`, still crashes if launching through terminal with `ulimit -c unlimited` being set

**Comment by sam-kirby** [comment]
> I'm having this same issue when loading the game as well
> 
> OS: Linux Mint 21.1 Launcher: MultiMC 5 I have attempted this issue with varying amounts of RAM(4GB-8GB)
> 
> Expected Outcome: Launches fine and loads a new world without any issue
> 
> Actual Outcome: Launches fine but crashes when loading a new world
> 
> heres the [Log Dump](https://github.com/DarkPacks/SevTech-Ages/files/12213581/hs_err_pid28748.log) after it crashing after trying without editing the `ulimit -c`, still crashes if launching through terminal with `ulimit -c unlimited` being set

I don't see a connection between your issue and the original issue. The original issue had an outdated version of Optifine that was incompatible with the version of the game being launched. If you are repeating this mistake, then the solution is simple; upgrade or remove Optifine.

The issue here seems to be a bug in a system library - possibly x11, maybe the desktop environment in use - triggered by the game trying to find what the default native file chooser is (aka the window that pops up when you click Save As). This is used by Antique Atlas if you choose to export atlas images.

The advice in the crash report to change the core size usage limit is only to allow a core dump to be performed. This dumps the contents of RAM used by a crashing program to disk in a separate file for analysis, but does not change the runtime behaviour of that program. If it crashed before doing that, it will crash after - except now it'll create a multi-gigabyte file and take a while to do it too.

I've not seen this before, and I run the game on Linux too. Ensure your system is up to date and that the file chooser is properly configured.

Later versions of Antique Atlas do not rely on the native file chooser as it is unreliable on MacOS due to threading restrictions on that platform. You could try updating Antique Atlas to version 4.6.3, though this may introduce other issues.

I am closing this issue as the original problem is seemingly solved, if you can't resolve your own problem from the information provided here please create a new issue.
