### ISSUE TITLE
Hunting Dimension not Loading Anything

### ISSUE THREAD

**Issue by skyhouse71** [DarkPacks/SevTech-Ages#4342]
## Bug Description
After I create the portal to the Hunting Dimension and go through, I spawn in a completely void void-world, no land, no nothing.  I thought that maybe I am just supposed to make a mob farm so I made a big platform out of cobble and only 1 zombie spawned.  Just 1 and then nothing else.  

Edit: Should have mentioned that the first time I crated the Hunting Dimension was when I was already in Age 4.

### Did this behavior use to work in the previous version?
Have only played on 3.2.0 Alpha 4

## Steps to Reproduce (for bugs)
1. Make portal to Hunting Dimension
2. Step through
3. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.2.0 Alpha 4
* Java Version: Version 8, Update 261
* Launcher Used: Curse
* Memory Allocated: 8G
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.2.0 Alpha 4
* Additional Content Installed: none

**Comment by louis71barker** [comment]
I have this same issue on Alpha 5, was there a way to fix this?

**Comment by sam-kirby** [comment]
This is deliberate - it's a sky block pack.

**Comment by ghost** [comment]
Sorry for opening this up again, after so much time... But I don't think the problem he was complaining about was the lack of land in the Hunting Dimension (because it's a sky block pack), but rather the lack of mob spawning once a platform is built.
Anyway, even if this wasn't the issue and I just misunderstood, could anyone explain the lack of mob spawning/efficiency in mobfarm in a dimension that should be full of mobs?
Thank you very much
