### ISSUE TITLE
broken start.bat

### ISSUE THREAD

**Issue by Kevengg** [DarkPacks/SevTech-Ages#4385]
## Bug Description
the start.bat file for the server install dos not work CMD pops opp for a fraction of a sec and nothing happens...
that is both for the 3.2.0 and the 3.1.7 folders

### Did this behavior use to work in the previous version?
dont know

## Steps to Reproduce (for bugs)
just runing the start.bat file on creation

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:.3.2.0 and 3.1.7
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:
* Operating System: WIN
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
There are a variety of reasons this may be happening; you must run the install batch file first, you must have accepted the Minecraft eula and you must have Java 8 installed with the server component the start script requests.

As I can't tell what your issue is from the limited information given here, I suggest you go to https://discord.gg/darkosto and post in the #sevtech-server-support channel  about this issue. You will likely get help there much quicker.

**Comment by Kevengg** [comment]
thanks for the help
