### ISSUE TITLE
Skyblock

### ISSUE THREAD

**Issue by JumperXxXCables** [DarkPacks/SevTech-Ages#4403]
## Bug Description

No Skyblock

### Did this behavior use to work in the previous version?

not sure this is the first time i played this mod. But i know it is a feature because i saw ChossenArcitech play it in skyblock.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:no log/no crash
* Crash Log:no log/no crash

## Client Information
* Modpack Version:3.1.2
* Java Version:Version 8 Update 271 build 1.8.0_271-b09
* Launcher Used:ATLauncher
* Memory Allocated:9k MB
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:3.1.2
* Additional Content Installed:forge version 14.23.5.2854 minecraft version 1.12.2

**Comment by Machine-Maker** [comment]
Well, there actually **is** a skyblock version of SevTech. You just didn't look very hard. It's made as a separate pack since there are substantial config differences. [Here is the CurseForge link](https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky).

Also, look at #4245 for more information on that.
