### ISSUE TITLE
"fatally missing registry entries" on SevTech server

### ISSUE THREAD

**Issue by Angelicalex** [DarkPacks/SevTech-Ages#4410]
## Bug Description

"Fatally missing registry entries" appearing on server connection screen. Me and 3 of my friends are unable to connect to the server. please help! 

### Did this behavior use to work in the previous version?

3.1.7 worked for me. Im on 3.2.0 right now.

## Steps to Reproduce (for bugs)

1. ?
2. ?
3. ?

## Logs

* Client/Server Log:
-client: [latest.log](https://github.com/DarkPacks/SevTech-Ages/files/5587970/latest.log)
-server: [latest.log](https://github.com/DarkPacks/SevTech-Ages/files/5587975/latest.log)

* Crash Log:

## Client Information
* Modpack Version: 3.2.0
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: None
* Shaders Enabled: None

## World Information
* Modpack Version world created in: 3.2.0
* Additional Content Installed: None

## Server Information
* Java Version: 8
* Operating System: Windows 10
* Hoster/Hosting Solution: ?
* Sponge (Non-Vanilla Forge) Server: ?

**Comment by sam-kirby** [comment]
There appear to be numerous problems with your server:
1. There is low drive space - this will cause corruption.
2. The configs don't match what we distribute. 
  a. Vanilla yoyos should be disabled (forcing tinkers), but your server has them enabled. Your client does not, and this is what is causing you to be disconnected.
  b. Large parts of PrimalCore should be disabled, but they have been enabled on your server. The logs warn this may cause world breakage.
3. Your advancements seem to have been corrupted.
4. Your server is unable to read various world related data files due to unexpected EOF.

Starting the server without enough free disk space has likely caused corruption to your configurations, as well as your world. Your best option is to free up drive space, install a fresh 3.2.0 server, and restore your world from a pre-upgrade backup.
