### ISSUE TITLE
Playerdata corrupted on death

### ISSUE THREAD

**Issue by blairwilson** [DarkPacks/SevTech-Ages#4487]
## Bug Description

After being killed by a Shadow Monster from Abyssalcraft the player is kicked from server and cannot relog

## Steps to Reproduce (for bugs)

1. Be player
2. Spawn Shadow Monster
3. Get killed

## Logs

* Client/Server Log:
* 
* Crash Log:
https://gist.github.com/HHServers/ec198051aa435e74f8136773f4635399

## Client Information
* Modpack Version:latest (only)
* Java Version: 8
* Launcher Used: MultiMC
* Memory Allocated:8GB
* Server/LAN/Single Player: Server
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:only
* Additional Content Installed:Sponge

## Server Information
* Java Version:1.8.0
* Operating System:Ubuntu groovy gorilla
* Hoster/Hosting Solution: OVH
* Sponge (Non-Vanilla Forge) Server:Sponge Yes

https://gist.github.com/HHServers/ec198051aa435e74f8136773f4635399

**Comment by sam-kirby** [comment]
From your log - 

You are killed by a Shadow Monster:
```
[16:47:32] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] blvxr was slain by Shadow Monster
```

The **server** crashes:
```
[16:47:34] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] The server you were previously on went down, you have been connected to a fallback server
```

You are connected to a fall back world:
```
[16:47:34] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] The server you were previously on went down, you have been connected to a fallback server
```

Which is identified as the "hub":
```
[16:47:34] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [STAFF] [blvxr] has moved to the [hub] server!
```

And then the client crashes because it's now receiving data in the wrong format as your hub server does not have JEID:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at net.minecraft.world.chunk.Chunk.setIntBiomeArray(Chunk.java:1661) ~[axw.class:?]
```

Am I following this correctly?

We cannot support connecting to "vanilla" hub worlds using SevTech client due to the need to have JEID. We would have to rewrite a lot of Minecraft to handle this edge case. Therefore the client crashing here is expected.

Why does the server crash though? Do you have that log?

**Comment by blairwilson** [comment]
You are following correctly. I thought the errors occurred in client before connection to hub but i may be wrong. No server crash it just prevents the player from being able to log back in - I tested and it happens on any death not just shadow monster kill

**Comment by sam-kirby** [comment]
There is no particular issue with dying on an unmodified SevTech server, so the issue is with your particular modifications or setup.

I suspect the issue is with the software you're using for networking together your servers (Bungee?). It is detecting a crash when one hasn't occurred, and moving users to the fallback. You might find clues as to why in its logs.

If a change to the pack is necessary to facilitate your setup, then let us know what it is and we will look at incorporating in the next update.

As it stands, this isn't something we can investigate as we don't have a reproducible version of your setup. Further, we do not investigate issues with modified packs as we don't have enough time as it is!

Please work directly with mod/plugin authors to resolve this and let us know if a change to the pack would be necessary.
