### ISSUE TITLE
Sevtech: Ages of the Sky - no surface ore

### ISSUE THREAD

**Issue by jrkaml** [DarkPacks/SevTech-Ages#4540]
## Bug Description

I'm playing Ages of the Sky. I created the world using "default" generation(creates a world on the ground, not islands in the sky), not "topography". When I reach Age 1, no surface ore spawns, so I cannot continue up the progression tree. 

### Did this behavior use to work in the previous version?

Not sure

## Steps to Reproduce (for bugs)

1. Create new survival world using "default" world generation. Here's my seed: 7971642052931264462
2. Switch to creative.  
3. Spawn in items to get to age 1.
4. Spawn in items up to "find coal/copper/tin" quest.
5. Fly around world and see zero surface ores in the specified biomes where age 1 ore should spawn.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.2.1-beta.1-skyblock
* Java Version:1.12.2
* Launcher Used:curseforge
* Memory Allocated:4gb
* Server/LAN/Single Player:Single Player
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:>3.2.1-beta.1-skyblock
* Additional Content Installed:none

**Comment by sam-kirby** [comment]
Is this an April Fools?

**Comment by sam-kirby** [comment]
In case it isn’t; there are two versions of this pack: SevTech Ages and SevTech Ages of the Sky. The key difference between them is world generation.

SevTech Ages uses a customised overworld where the biomes are arranged according to temperature on the North/South axis and humidity on the East/West axis. Geolosys handles ore generation.

SevTech Ages of the Sky uses Topography; the whole overworld and several other dimensions are replaced with a custom sky islands map. The islands have cores of ore determined by their biome. Topography is responsible for ore generation in this pack, even though the blocks themselves come from Geolosys still.

As a result, playing SevTech Ages of the Sky with Normal world generation results in no ore spawn by design. This is not going to be changed as it would lead to undesired effects on the custom map.

If you want to play SevTech in a more standard overworld, play the original version of the pack available here: https://www.curseforge.com/minecraft/modpacks/sevtech-ages

**Comment by jrkaml** [comment]
No it was a legit question. I had both regular sevtech and Sky and hadn't played either. Started a server and we ran into this issue. I'm glad we got it figured out before we got too far!
Thx
