### ISSUE TITLE
why is auto jump always on

### ISSUE THREAD

**Issue by Maikeru0527** [DarkPacks/SevTech-Ages#4549]
I dont know any one who uses auto jump so for it to be on and i cant turn it off it gets me pissed off

**Comment by sam-kirby** [comment]
Autojump is locked OFF precisely because nobody in their right mind likes auto jump.

Your player has their step height set to one block just like horses do - this means you can run up and down inclines with ease, and we've found many players like moving around like this. It's much smoother than auto jump, and is much less likely to trigger accidentally.

This is provided by the mod Cyclic. You can toggle it on or off by eating an Apple of Lofty Stature.
