### ISSUE TITLE
Can't Open Module Manager

### ISSUE THREAD

**Issue by Hamsterpouch** [DarkPacks/SevTech-Ages#4624]
## Bug Description
I can't open the Module Manager. I press H in JEI, inventory, or just pressing it and it doesn't open. I made sure to wear a space suit with a module in my inventory and it still didn't work.I then checked my keybinding, it was not conflicting with any others. I have Extraplanets 1.12.2-0.7.3. 

### Did this behavior use to work in the previous version?
It might be Extraplanets itself, I have 45 other mods.

Steps to Reproduce

I don't think there's a way to reproduce this bug
Maybe getting the same mods I have will reproduce this, other then that I don't know aything else

## Logs

* Client/Server Log:This bug doesn't cause a crash
* Crash Log:This bug doesn't cause a crash

## Client Information
* Java Version:64bit 241 (not entirely sure)
* Launcher Used:Default minecraft launcher. (Whatever the latest version was since 8/27/21)
* Memory Allocated:5 of my 8 gig. It crashes a lot because I don't have enough.
* Server/LAN/Single Player: single player (haven't tested LAN)
* Optifine Installed:Yes, optifine is in the mods directory
* Shaders Enabled:No shaders are enabled

## World Information
* Modpack Version world created in:No modpack, just a bunch of mods on 1.12.2.
* Additional Content Installed:45 other mods.

**Comment by Hamsterpouch** [comment]
Im sorry, what did I miss?

**Comment by sam-kirby** [comment]
> Im sorry, what did I miss?

The bot is very sensitive, everything must be formatted as it expects - it closed your issue because "Steps to Reproduce" was not formatted as a title. For this reason I do check every issue the bot closes.

In this case, I feel like your issue may be in the wrong place. You claim not to be playing a modpack but this is the issue page for a modpack - specifically SevTech Ages.

In our pack, the module manager is available and is bound to `H` by default. Pressing `H` while in game (not in any other menu) opens the module manager. What action are we supposed to take based on your issue report?
