### ISSUE TITLE
Together Forever don't work on LAN server / only one player can get achievements

### ISSUE THREAD

**Issue by I3estOFF** [DarkPacks/SevTech-Ages#4653]
## Bug Description

Only host of the lan server can get achievements when in same team

### Did this behavior use to work in the previous version?

dont know

## Steps to Reproduce (for bugs)

1. join server
2. join team
3. only one player can get achievements

## Logs

* Client/Server Log:
* Crash Log:
no crashes

## Client Information
* Modpack Version: newest
* Java Version: 8 
* Launcher Used: curse forge
* Memory Allocated: 8gb
* Server/LAN/Single Player: LAN
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in: yes
* Additional Content Installed: no

**Comment by sam-kirby** [comment]
There are a variety of issues when using Open To LAN that can be traced back to Mojang's inconsitent implementation of features. As a result, many mod authors choose not to support it, including the author of Together Forever. Due to this and other issues, we do not recommend using Open To LAN. Playing multiplayer is best achieved by using the dedicated server. You can run this on the same system you are playing on if you have sufficient RAM. The server needs about 4GB for a 2 player world (+0.5GB per additional player).
