### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by Zeek-AZ** [DarkPacks/SevTech-Ages#4688]
## Bug Description
When loaded into my server, textures on all blocks are not loading. All textures are transparent. I can place a block inside of the messed up chunck and textures will load. When I try to destroy a block such as a dirt block, the texture does not get destroyed but the block itself does. I launched a single player world and did not have these issues. I am using Forge Server 14.23.5.2860 on Minecraft 1.12.2 with SevTechAges 3.2.3

### Did this behavior use to work in the previous version?
This is my first time on this server version.

## Steps to Reproduce (for bugs)
1.Added mods to mod folder locally and in server folder
2.launched server
3.logged into server - no textures

## Logs

* Client/Server Log:[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/8171698/latest.log)

* Crash Log:

## Client Information
* Modpack Version:3.2.3
* Java Version:1.8.0_51
* Launcher Used:Minecraft Launcher
* Memory Allocated:6GB
* Server/LAN/Single Player:Server
* Optifine Installed:?
* Shaders Enabled:Tried with enabled and without enabled - no change
* 
## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
There are significant issues with your client setup evident from your logs. You indicate you only included the mods folder, but this is useless on its own - you will also need the configuration, resources and scripts.

Your client also indicates it is connecting to a vanilla server:

```
[09:51:42] [Netty Client IO #0/INFO] [FML]: [Netty Client IO #0] Client side vanilla connection established
```

And this is exactly the behaviour we would expect to see when connecting to a vanilla server as the client is expecting a modified protocol.

I suggest you use a launcher such as multimc to setup the client and follow the guide for setting up a server. If you need assistance, it would be best to ask on Discord at https://discord.gg/darkosto rather than opening issues here.
