### ISSUE TITLE
age 1 ores not spawning at all.

### ISSUE THREAD

**Issue by wolfbattlepants** [DarkPacks/SevTech-Ages#4693]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:<!3.2.3>
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Which variant of the pack did you download - [SevTech: Ages](https://www.curseforge.com/minecraft/modpacks/sevtech-ages) or [SevTech: Ages of the Sky](https://www.curseforge.com/minecraft/modpacks/sevtech-ages-ages-of-the-sky)?

If you are trying to play ST:AotS with the skyblock disabled then this is expected behaviour; play ST:A instead.

**Comment by wolfbattlepants** [comment]
ah okay thanks i have figured it out!
